### ISSUE TITLE
Building wheel for pycocotools (setup.py) ... error

### ISSUE THREAD

**Issue by windskyxb** [7eu7d7/genshin_auto_fish#10]
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI                                         Cloning https://github.com/philferriere/cocoapi.git to c:\users\winds\appdata\local\temp\pip-req-build-1h2nkaa4         Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\winds\AppData\Local\Temp\pip-req-build-1h2nkaa4'                                                                                                             Resolved https://github.com/philferriere/cocoapi.git to commit 2929bd2ef6b451054755dfd7ceb09278f935f7ad               Building wheels for collected packages: pycocotools                                                                       Building wheel for pycocotools (setup.py) ... error                                                                     ERROR: Command errored out with exit status 1:                                                                           command: 'C:\Users\winds\.conda\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\winds\\AppData\\Local\\Temp\\pip-req-build-1h2nkaa4\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\winds\\AppData\\Local\\Temp\\pip-req-build-1h2nkaa4\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\winds\AppData\Local\Temp\pip-wheel-u7e0novk'                                                                               cwd: C:\Users\winds\AppData\Local\Temp\pip-req-build-1h2nkaa4\PythonAPI                                            Complete output (13 lines):                                                                                             running bdist_wheel                                                                                                     running build                                                                                                           running build_py                                                                                                        creating build                                                                                                          creating build\lib.win-amd64-3.6                                                                                        creating build\lib.win-amd64-3.6\pycocotools                                                                            copying pycocotools\coco.py -> build\lib.win-amd64-3.6\pycocotools                                                      copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.6\pycocotools                                                  copying pycocotools\mask.py -> build\lib.win-amd64-3.6\pycocotools                                                      copying pycocotools\__init__.py -> build\lib.win-amd64-3.6\pycocotools                                                  running build_ext                                                                                                       building 'pycocotools._mask' extension                                                                                  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/                                                                                    ----------------------------------------                                                                                ERROR: Failed building wheel for pycocotools                                                                            Running setup.py clean for pycocotools                                                                                  ERROR: Command errored out with exit status 1:                                                                           command: 'C:\Users\winds\.conda\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\winds\\AppData\\Local\\Temp\\pip-req-build-1h2nkaa4\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\winds\\AppData\\Local\\Temp\\pip-req-build-1h2nkaa4\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all                 cwd: C:\Users\winds\AppData\Local\Temp\pip-req-build-1h2nkaa4                                                      Complete output (11 lines):                                                                                             Traceback (most recent call last):                                                                                        File "<string>", line 1, in <module>                                                                                    File "C:\Users\winds\AppData\Local\Temp\pip-req-build-1h2nkaa4\PythonAPI\setup.py", line 25, in <module>                  cythonize(ext_modules)                                                                                                File "C:\Users\winds\.conda\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 972, in cythonize           aliases=aliases)                                                                                                      File "C:\Users\winds\.conda\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list                                                                                                                       for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):              File "C:\Users\winds\.conda\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty            raise ValueError(error_msg)                                                                                         ValueError: 'pycocotools/_mask.pyx' doesn't match any files                                                             ----------------------------------------                                                                                ERROR: Failed cleaning build dir for pycocotools                                                                      Failed to build pycocotools                                                                                             Installing collected packages: pycocotools                                                                                  Running setup.py install for pycocotools ... error                                                                      ERROR: Command errored out with exit status 1:                                                                           command: 'C:\Users\winds\.conda\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\winds\\AppData\\Local\\Temp\\pip-req-build-1h2nkaa4\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\winds\\AppData\\Local\\Temp\\pip-req-build-1h2nkaa4\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\winds\AppData\Local\Temp\pip-record-5_cc_gg0\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\winds\.conda\envs\ysfish\Include\pycocotools'                                                         cwd: C:\Users\winds\AppData\Local\Temp\pip-req-build-1h2nkaa4\PythonAPI                                            Complete output (6 lines):                                                                                              running install                                                                                                         running build                                                                                                           running build_py                                                                                                        running build_ext                                                                                                       building 'pycocotools._mask' extension                                                                                  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/                                                                                    ----------------------------------------                                                                            ERROR: Command errored out with exit status 1: 'C:\Users\winds\.conda\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\winds\\AppData\\Local\\Temp\\pip-req-build-1h2nkaa4\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\winds\\AppData\\Local\\Temp\\pip-req-build-1h2nkaa4\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\winds\AppData\Local\Temp\pip-record-5_cc_gg0\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\winds\.conda\envs\ysfish\Include\pycocotools' Check the logs for full command output.                                                                                               WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.                      Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.                           To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.                              ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by windskyxb** [comment]
![屏幕截图(11).png](https://i.loli.net/2021/09/21/Fkwja6YMXdszG5r.png)
![屏幕截图(12).png](https://i.loli.net/2021/09/21/9ne1mDdbjAJBQYW.png)

**Comment by 7eu7d7** [comment]
需要安装vc++编译环境，可以参考https://github.com/7eu7d7/genshin_auto_fish/issues/7
