### ISSUE TITLE
运行yolox提示没有'SyncBatchNorm'

### ISSUE THREAD

**Issue by kalmiras** [7eu7d7/genshin_auto_fish#105]
![question](https://user-images.githubusercontent.com/45911006/134793857-c37f8fec-5043-4714-8014-2618a8475d1b.PNG)
是我cuda8.0版本不配运行吗？

**Comment by XueJiang16** [comment]
你这是torch版本太低

**Comment by kalmiras** [comment]
就是版本问题，8.0cuda版本的pytorch没有SysBatchNorm
