### ISSUE TITLE
运行python yolox_tools/train.py -f yolox/exp/yolox_tiny_fish.py -d 1 -b 8 --fp16 -o -c weights/yolox_tiny.pth出错

### ISSUE THREAD

**Issue by q764447890** [7eu7d7/genshin_auto_fish#108]
![错误](https://user-images.githubusercontent.com/26245718/134807824-24451ff2-75b8-4cc2-b3ba-11f372fea9ec.PNG)

**Comment by q764447890** [comment]
![2](https://user-images.githubusercontent.com/26245718/134807843-006d0cb2-e590-4ee8-9ea4-216b7faddd2f.PNG)
将yolox/exp/yolox_tiny_fish.py中的self.data_dir的值改为解压后2个文件夹所在的路径。
这是我的地址C:\Users\Home\genshin_auto_fish\fish_dataset
怎么修改

**Comment by milkbing** [comment]
![image](https://user-images.githubusercontent.com/49283001/134811742-eea96d51-6a89-4352-9bf3-28c7dd3a39aa.png)

**Comment by milkbing** [comment]
![image](https://user-images.githubusercontent.com/49283001/134811783-a5975a12-6a9d-454c-b84f-565a3403bbf4.png)
这样修改。
