### ISSUE TITLE
YOLOX训练工作流程：出错

### ISSUE THREAD

**Issue by milkbing** [7eu7d7/genshin_auto_fish#109]
![image](https://user-images.githubusercontent.com/49283001/134813886-60894cc1-643e-46a5-9861-d9d37348406f.png)

报错内容：RuntimeError: DataLoader worker (pid(s) 22660, 20952, 19692, 21452) exited unexpectedly
使用的是YOLOX训练工作流程中的训练代码
求大佬解答

**Comment by milkbing** [comment]
![image](https://user-images.githubusercontent.com/49283001/134814401-eec335f4-3746-43a2-babc-321550e1c78a.png)
这是我找到的（File "D:\anaconda\envs\ysfish\lib\site-packages\torch\utils\data\dataloader.py", line 885），不知道这个有没有帮助。

**Comment by pianfanshaan** [comment]
有可能是cuda版本问题 你可以试试找合适版本的cuda

**Comment by milkbing** [comment]
谢谢你的回答，不过我不进行研究了，可以给其他遇到此问题的人做参考。
