### ISSUE TITLE
能钓但又完全没钓上来

### ISSUE THREAD

**Issue by Jasonz27** [7eu7d7/genshin_auto_fish#113]
yolox训练跳过，直接下载weights里的3个.pth文件丢进去weights。
然后dqn仿真运行
最后就运行钓鱼ai（gpu），发现可以正常让鱼吃饵，但是最后却不进行收钩（钓的是一开始的那种）

鱼吃饵后就出现这个报错
![1](https://user-images.githubusercontent.com/69143100/134865217-d86f5703-3240-489f-94ec-ece0f2fc8a42.png)

**Comment by xleizi** [comment]
我也是这样，一模一样的问题，训练过拉杆之后还是不行

**Comment by thenew01** [comment]
我的也一样，第一次收钩，力度条蓄满力，不调整。后面几次只扔杆不收杆

**Comment by Yuheeeng** [comment]
我的也是第一次拉杆拉满，然后失败，之后就再没拉过杆

**Comment by Jasonz27** [comment]
改了下代码，半自动钓鱼。

没有训练，直接使用提供的weights。weights文件夹放入best_tiny3.pth和fish_genshin_net.pth这两个文件，output文件夹下放入fish_sim_net.pth文件（没有output文件夹就新建）。都是放在genshin_auto_fish目录下。

然后在genshin_auto_fish下找到fishing.py文件进行修改，如下图
![QQ截图20211005003434](https://user-images.githubusercontent.com/69143100/135889766-1924c14f-c521-45d5-a837-81376b2e343f.png)
按r是进行收钩，钓完上来后按p退出那个循环，然后又等鱼咬钩，如此循环

全屏操作。不过我全屏的时候发现只能过总蓄力条的一半多一点，大概三分之二的范围是可以自动的（我的全屏分辨率是2160×1440），过了就不会动了，这时候就要自己手点了。如果全屏不行的话就弄成1920×1080，这样虽然比全屏的范围小了点，但还算可以。以上是我的情况。
