### ISSUE TITLE
同pycocotools无法安装

### ISSUE THREAD

**Issue by Vurks** [7eu7d7/genshin_auto_fish#118]
![MOMKV1U37U6N6S{KUFDAHCQ](https://user-images.githubusercontent.com/91673508/135455019-f839fbf8-fb39-428e-a489-093e394cb3c9.png)
![76NRY@_EH (~(MWYO@ZOBM9](https://user-images.githubusercontent.com/91673508/135455043-02c39004-c487-4a33-90dc-e49c200b1bb6.png)

一开始提示运行Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\Ameriam\AppData\Local\Temp\pip-req-build-6gj7mmhg'指令错误，于是单独用git clone -q https://github.com/philferriere/cocoapi.git试了一遍，结果再用python requirements.py --cuda 110安装的时候就提示这个了

**Comment by zhangp12** [comment]
我也碰上了这个问题，先尝试只安装Visual C++ 2015 build tools并没有解决问题。然后用官方的visual studio build tools installer https://visualstudio.microsoft.com/visual-cpp-build-tools/ 安装了Visual studio build tools 2019 (optional里加上了windows 10 sdk)，总共6个G，然后就没问题了。

**Comment by shaohua-debug** [comment]
> 我也碰上了这个问题，先尝试只安装Visual C++ 2015 build tools并没有解决问题。然后用官方的visual studio build tools installer https://visualstudio.microsoft.com/visual-cpp-build-tools/ 安装了Visual studio build tools 2019 (optional里加上了windows 10 sdk)，总共6个G，然后就没问题了。

补充，Visual studio build tools 2019要安装最新版，默认的不行
