### ISSUE TITLE
python requirements.py报错

### ISSUE THREAD

**Issue by suppersky** [7eu7d7/genshin_auto_fish#123]
Successfully installed numpy-1.19.5
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1, 1.7.1+cpu, 1.7.1+cu101, 1.7.1+cu110, 1.8.0, 1.8.0+cpu, 1.8.0+cu101, 1.8.0+cu111, 1.8.1, 1.8.1+cpu, 1.8.1+cu101, 1.8.1+cu102, 1.8.1+cu111, 1.9.0, 1.9.0+cpu, 1.9.0+cu102, 1.9.0+cu111, 1.9.1, 1.9.1+cpu, 1.9.1+cu102, 1.9.1+cu111)
ERROR: No matching distribution found for torch==1.7.0+cpu

---------------------------------------------------------------------------------------
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\10344\appdata\local\temp\pip-req-build-3rn97eag
  Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\10344\AppData\Local\Temp\pip-req-build-3rn97eag'
  Resolved https://github.com/philferriere/cocoapi.git to commit 2929bd2ef6b451054755dfd7ceb09278f935f7ad
Using legacy 'setup.py install' for pycocotools, since package 'wheel' is not installed.
Installing collected packages: pycocotools
    Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\software\progrem\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\10344\\AppData\\Local\\Temp\\pip-req-build-3rn97eag\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\10344\\AppData\\Local\\Temp\\pip-req-build-3rn97eag\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\10344\AppData\Local\Temp\pip-record-08idondy\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\software\progrem\Python39\Include\pycocotools'
         cwd: C:\Users\10344\AppData\Local\Temp\pip-req-build-3rn97eag\PythonAPI
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\pycocotools
    copying pycocotools\coco.py -> build\lib.win-amd64-3.9\pycocotools
    copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.9\pycocotools
    copying pycocotools\mask.py -> build\lib.win-amd64-3.9\pycocotools
    copying pycocotools\__init__.py -> build\lib.win-amd64-3.9\pycocotools
    running build_ext
    building 'pycocotools._mask' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\software\progrem\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\10344\\AppData\\Local\\Temp\\pip-req-build-3rn97eag\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\10344\\AppData\\Local\\Temp\\pip-req-build-3rn97eag\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\10344\AppData\Local\Temp\pip-record-08idondy\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\software\progrem\Python39\Include\pycocotools' Check the logs for full command output.

**Comment by qilishidai** [comment]
你要安装Visual C++ 2015 build tools，要通过这个https://go.microsoft.com/fwlink/?LinkId=691126 安装Visual C++ 2015 build tools，但是要全局翻墙还不一定能下下来。你可以看一下这个https://blog.csdn.net/qq_15158911/article/details/107887490 这里提供了Visual C++ 2015 build tools完整的iso文件链接：https://pan.baidu.com/s/19F4YurwwZ5A9WF5txzMZoQ 提取码：ka7q
