### ISSUE TITLE
YOLOX训练时出现OSError

### ISSUE THREAD

**Issue by qiuqiu-2** [7eu7d7/genshin_auto_fish#129]
说是无效的参数，就只有YOLOX训练时会报错，其它训练没问题，还有就是允许AI的时候，只会自动转动视角，然后抛竿是秒抛，抛了以后秒收回，然后继续转动视角，不太懂
OSError: [Errno 22] Invalid argument: 'D:\x07naconda3\\envs\\ysfish\x0cish-dataset\\annotations\\fish_p2_75+jam.json'

**Comment by Yuheeeng** [comment]
我也碰到了：
OSError: [Errno 22] Invalid argument: 'D:\\Game Editing Tools\x0cish-dataset\\annotations\\fish_p2_75+jam.json'

**Comment by 7eu7d7** [comment]
数据集没设置好，只是也可以不用训练
