### ISSUE TITLE
钓鱼失败

### ISSUE THREAD

**Issue by wudih146** [7eu7d7/genshin_auto_fish#13]

**Comment by wudih146** [comment]
命令行有输出...按R键并且原神界面已全屏
![91YRSYNR1YRUNQH1 3I39E1](https://user-images.githubusercontent.com/11288525/134136969-467c28c1-1146-41dd-a536-a57f8880a1c6.png)

**Comment by 7eu7d7** [comment]
单独开命令行，要以管理员权限运行。

**Comment by wudih146** [comment]
谢谢
