### ISSUE TITLE
小白求帮忙

### ISSUE THREAD

**Issue by sushang-data** [7eu7d7/genshin_auto_fish#135]
我是计算机新生，进行到依赖库安装不知道啥意思了，前面的通过bing也找到了解决方法（应该是做好了，我也不确定），这里面提到的东西也就python稍微接触过，别的是啥都不知道，有大佬能详细的帮我解释一下咋搞吗？谢谢

**Comment by lNeverl** [comment]
就是照着输入代码就好了    有一些python的包需要安装      输入之后会自动安装  那个包安不上就要单独安装  去解决问题

**Comment by sushang-data** [comment]
那个“切换命令行到本工程所在目录”，是找到genshin_auto_fish的文件夹吗

**Comment by sushang-data** [comment]
OK，往下走了，谢谢大佬
