### ISSUE TITLE
init ok but 没有反应  命令行终端有输出 游戏界面视角会变，推测是左击起效

### ISSUE THREAD

**Issue by Aprodebug** [7eu7d7/genshin_auto_fish#137]
init ok  有输出 ，使用的是默认权重文件  不知道问题  电脑分辨率使用1920*1080  游戏全屏
![KPF$ZZ)EN78O)E0`8 Y 0W](https://user-images.githubusercontent.com/39954869/136377542-2ef099e9-e3b6-4c90-a48a-aead11364fdd.png)
![NS89)EK$7(D8ESQ3O_NV@07](https://user-images.githubusercontent.com/39954869/136377549-36874b8b-7555-44b7-8a92-0a6a4d7cac4a.png)
![{RDO(MD51%S)XA$ZNCP@IRH](https://user-images.githubusercontent.com/39954869/136377551-f10419c2-37c6-4b86-bf27-364136243d8d.png)
唯一的反应就是视角会偏移一点

**Comment by 7eu7d7** [comment]
进入钓鱼模模式后按R，初始鱼饵选钓花鳉的
