### ISSUE TITLE
【小白求助】执行python requirements.py失败

### ISSUE THREAD

**Issue by 410091174** [7eu7d7/genshin_auto_fish#142]
下图error部分，我电脑没pip-req-build-a00t8lh8这个文件（文件夹）/(ㄒoㄒ)/~~
![R%~6IE(5 T_NQD{%8UOI6{O](https://user-images.githubusercontent.com/91724282/136647750-812c6963-f318-40aa-902f-66afb63780aa.png)

**Comment by sushang-data** [comment]
> 一般问题是网络问题 有代理的话可以挂一下 不然就多试几次

我本来也是和楼主一样的，换了手机热点，报了一大段红字，下面是错误部分，共三块大片红字
![image](https://user-images.githubusercontent.com/82026012/136680309-dca99835-f950-42f7-bba9-fa727c8ca358.png)
![image](https://user-images.githubusercontent.com/82026012/136680321-dd7fa5a2-fa3e-4c18-81c4-dcd609b783a8.png)

**Comment by wuyehuanq** [comment]
这一步 是在安装cocoapi ，我是直接将这个下载到本地，尝试进行安装，目前遇到报错

**Comment by 410091174** [comment]
> > 一般问题是网络问题 有代理的话可以挂一下 不然就多试几次
> 
> 我本来也是和楼主一样的，换了手机热点，报了一大段红字，下面是错误部分，共三块大片红字 ![image](https://user-images.githubusercontent.com/82026012/136680309-dca99835-f950-42f7-bba9-fa727c8ca358.png) ![image](https://user-images.githubusercontent.com/82026012/136680321-dd7fa5a2-fa3e-4c18-81c4-dcd609b783a8.png)

  我有时候也是这样

**Comment by 410091174** [comment]
> 这一步 是在安装cocoapi ，我是直接将这个下载到本地，尝试进行安装，目前遇到报错

我也是把cocoapi下载到了本地，不过不会安装

**Comment by 410091174** [comment]
> 一般问题是网络问题 有代理的话可以挂一下 不然就多试几次

有开免费代理，没啥用啊，一直都这样

**Comment by wuyehuanq** [comment]
> > 这一步 是在安装cocoapi ，我是直接将这个下载到本地，尝试进行安装，目前遇到报错
> 
> 我也是把cocoapi下载到了本地，不过不会安装



> > 这一步 是在安装cocoapi ，我是直接将这个下载到本地，尝试进行安装，目前遇到报错
> 
> 我也是把cocoapi下载到了本地，不过不会安装

进入到cocoapi 的目录 运行python setup.py install 就行
