### ISSUE TITLE
显存不足

### ISSUE THREAD

**Issue by wuyehuanq** [7eu7d7/genshin_auto_fish#155]
好不容易部署到最后，现在提示显存不足，我电脑配置CPU I7-7700HQ 内存24G 显卡1050ti 2G显存，我的电脑还能继续往下跑吗？不适用GPU ,使用CPU?
![image](https://user-images.githubusercontent.com/91661075/137427812-0ff3895c-0a20-4b6e-affd-0edfc2e13129.png)

**Comment by wuyehuanq** [comment]
这个问题 我没有解决，你这边解决了吗

**Comment by LuoRenMu** [comment]
yolo 可以调的吧

**Comment by wuyehuanq** [comment]
> yolo 可以调的吧

这个怎么调呀，可以指导一下嘛

**Comment by 7eu7d7** [comment]
2G显存跑训练不太够，直接用预训练的模型吧
