### ISSUE TITLE
from pycocotools.coco import COCO ModuleNotFoundError: No module named 'pycocotools'

### ISSUE THREAD

**Issue by hotpotlover-yang** [7eu7d7/genshin_auto_fish#163]
![image](https://user-images.githubusercontent.com/63411913/138486550-8f5a35b7-9ca2-453f-a3df-26d215f1464d.png)

**Comment by Eudonomia** [comment]
python的pycocotools没安装，安装以及问题解决方法参考https://www.jianshu.com/p/8658cda3d553，注意pip版本
