### ISSUE TITLE
运行YOLOX训练工作流程出错

### ISSUE THREAD

**Issue by wannerzhu** [7eu7d7/genshin_auto_fish#165]
![image](https://user-images.githubusercontent.com/74132270/138888491-16ab98bc-2550-4082-a7f5-022b9ee53743.png)
求助，yolox训练进程出错，导致后续运行钓鱼AI时无法进行

**Comment by phcbest** [comment]
> ![image](https://user-images.githubusercontent.com/74132270/138888491-16ab98bc-2550-4082-a7f5-022b9ee53743.png) 求助，yolox训练进程出错，导致后续运行钓鱼AI时无法进行

同样的错误
 ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (16184), thread 'MainThread' (3736):
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by 7eu7d7** [comment]
训练需要使用显卡，要安装CUDA编译yolox
