### ISSUE TITLE
安装配置环境最后一步出错，望能解决

### ISSUE THREAD

**Issue by duanfayoung** [7eu7d7/genshin_auto_fish#166]
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\fayoung\appdata\local\temp\pip-gipz91xn-build
Installing collected packages: pycocotools
  Running setup.py install for pycocotools ... error
    Complete output from command D:\Environment\Anaconda3\envs\ysfish\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\fayoung\\AppData\\Local\\Temp\\pip-gipz91xn-build\\PythonAPI\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\fayoung\AppData\Local\Temp\pip-inyjwwup-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pycocotools
    copying pycocotools\coco.py -> build\lib.win-amd64-3.6\pycocotools
    copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.6\pycocotools
    copying pycocotools\mask.py -> build\lib.win-amd64-3.6\pycocotools
    copying pycocotools\__init__.py -> build\lib.win-amd64-3.6\pycocotools
    running build_ext
    building 'pycocotools._mask' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\pycocotools
    creating build\temp.win-amd64-3.6\common
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Environment\Anaconda3\envs\ysfish\lib\site-packages\numpy\core\include -I../common -ID:\Environment\Anaconda3\envs\ysfish\include -ID:\Environment\Anaconda3\envs\ysfish\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.6\Release\pycocotools/_mask.obj
    _mask.c
    d:\environment\anaconda3\envs\ysfish\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    pycocotools/_mask.c(3311): warning C4244: “=”: 从“Py_ssize_t”转换到“siz”，可能丢失数据
    pycocotools/_mask.c(3721): warning C4244: “函数”: 从“npy_intp”转换到“siz”，可能丢失数据
    pycocotools/_mask.c(6728): warning C4244: “=”: 从“npy_intp”转换到“siz”，可能丢失数据
    pycocotools/_mask.c(7486): warning C4244: “=”: 从“Py_ssize_t”转换到“siz”，可能丢失数据
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Environment\Anaconda3\envs\ysfish\lib\site-packages\numpy\core\include -I../common -ID:\Environment\Anaconda3\envs\ysfish\include -ID:\Environment\Anaconda3\envs\ysfish\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.6\Release\../common/maskApi.obj
    maskApi.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\Environment\Anaconda3\envs\ysfish\libs /LIBPATH:D:\Environment\Anaconda3\envs\ysfish\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" /EXPORT:PyInit__mask build\temp.win-amd64-3.6\Release\pycocotools/_mask.obj build\temp.win-amd64-3.6\Release\../common/maskApi.obj /OUT:build\lib.win-amd64-3.6\pycocotools\_mask.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\pycocotools\_mask.cp36-win_amd64.lib
    _mask.obj : warning LNK4197: 多次指定导出“PyInit__mask”；使用第一个规范
      正在创建库 build\temp.win-amd64-3.6\Release\pycocotools\_mask.cp36-win_amd64.lib 和对象 build\temp.win-amd64-3.6\Release\pycocotools\_mask.cp36-win_amd64.exp
    正在生成代码
    已完成代码的生成
    LINK : fatal error LNK1158: 无法运行“rc.exe”
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

    ----------------------------------------
Command "D:\Environment\Anaconda3\envs\ysfish\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\fayoung\\AppData\\Local\\Temp\\pip-gipz91xn-build\\PythonAPI\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\fayoung\AppData\Local\Temp\pip-inyjwwup-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\fayoung\AppData\Local\Temp\pip-gipz91xn-build\PythonAPI

**Comment by HuYo-OS** [comment]
解决了吗

**Comment by HuYo-OS** [comment]
如果没有解决的话可以试试下载这个链接：https://pan.baidu.com/s/1SB96HL8PUOemdMv0kr7BDA 
提取码：rcdl ；放到C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin 【我这里为默认路径】文件夹下，当然，你得先安装Microsoft Visual Studio 14.0
