### ISSUE TITLE
ImportError: yolox/exp/yolox_tiny_fish.py doesn't contains class named 'Exp' 用相对路径试试 

### ISSUE THREAD

**Issue by aaaihw** [7eu7d7/genshin_auto_fish#167]
ImportError: yolox/exp/yolox_tiny_fish.py doesn't contains class named 'Exp' 

请问用相对路径试试 是什么意思？我不太懂

_Originally posted by @windskyxb in https://github.com/7eu7d7/genshin_auto_fish/issues/70#issuecomment-925645020_

**Comment by zzbjyhy** [comment]
请问您解决了吗，我也是这个问题

**Comment by USTBZcb** [comment]
在服务器上，可以用相对路径。如果是在本机上，或者是在本机上运行服务器程序，用在服务器上的绝对路径
