### ISSUE TITLE
安装yolox出错

### ISSUE THREAD

**Issue by mcx1932446170** [7eu7d7/genshin_auto_fish#179]
(ysfish) C:\Users\Admin\genshin_auto_fish>python setup.py develop
running develop running egg_info
writing yolox.egg-info\PKG-INFO
writing dependency_links to yolox.egg-info\dependency_links.txt
writing top-level names to yolox.egg-info\top_level.txt

D:\Ananconda\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))

reading manifest file 'yolox.egg-info\SOURCES.txt'
writing manifest file 'yolox.egg-info\SOURCES.txt'
running build_ext

D:\Ananconda\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:316: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')

copying build\lib.win-amd64-3.6\yolox\_C.cp36-win_amd64.pyd -> yolox
Creating d:\ananconda\envs\ysfish\lib\site-packages\yolox.egg-link (link to .)
yolox 0.1.0 is already the active version in easy-install.pth

Installed c:\users\admin\genshin_auto_fish
Processing dependencies for yolox==0.1.0
Finished processing dependencies for yolox==0.1.0

(ysfish) C:\Users\Admin\genshin_auto_fish>
在前面一步运行python requirements.py的时候我的py3.6运行不了，就用原来的3.7运行了。到了python setup.py develop用3.7bug贼多，我换回了py3.6运行还是有两个问题，就是上面贴出来的。我去根目录看了一下D:\Ananconda\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py这个文件其实是有的，大佬们救救我

**Comment by mcx1932446170** [comment]
第二个error有人说是没有配置vc环境的锅，我配置了下确实没了，但第一个还不知道怎么弄

**Comment by mcx1932446170** [comment]
def __init__(self, *args, **kwargs) -> None:
        super(BuildExtension, self).__init__(*args, **kwargs)
        self.no_python_abi_suffix = kwargs.get("no_python_abi_suffix", False)

        self.use_ninja = kwargs.get('use_ninja', True)
        if self.use_ninja:
            # Test if we can use ninja. Fallback otherwise.
            msg = ('Attempted to use ninja as the BuildExtension backend but '
                   '{}. Falling back to using the slow distutils backend.')
            if not is_ninja_available():
                warnings.warn(msg.format('we could not find ninja.'))
                self.use_ninja = False
这个是cpp_extension.py里那段代码，不知道是出错了还是正常warning

**Comment by Cathgao** [comment]
ninja的可以不用管，那个只是换成ninja去调用编译。装好vs能编译出yolox就可以了。
你想用ninja就pip install ninja就行了
