### ISSUE TITLE
get_score一直为0导致无法判断钓鱼完成

### ISSUE THREAD

**Issue by kuzen** [7eu7d7/genshin_auto_fish#180]
钓完第一条鱼之后发现无法结束，调试之后发现get_score一直为0导致无法判断钓鱼完成。
我改大了阈值，改为50之后能用了。
https://github.com/7eu7d7/genshin_auto_fish/blob/8be30c321db67af9b436b1759f66b418338ff858/fisher/environment.py#L198

类似问题 #172

另外Fishing.show_det建议默认为False吧，给我硬盘写了几千张图片我才发现。。

**Comment by thanksshu** [comment]
可能是std_color的问题，我设置了`[255, 250, 190]`后有很大改善。
