### ISSUE TITLE
安装pycocotools时报错

### ISSUE THREAD

**Issue by 1045925330** [7eu7d7/genshin_auto_fish#182]
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\xh104\appdata\local\temp\pip-req-build-k7j7dxcd
  Running command git clone --filter=blob:none -q https://github.com/philferriere/cocoapi.git 'C:\Users\xh104\AppData\Local\Temp\pip-req-build-k7j7dxcd'
  Resolved https://github.com/philferriere/cocoapi.git to commit 2929bd2ef6b451054755dfd7ceb09278f935f7ad
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\ProgramData\Anaconda3\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xh104\\AppData\\Local\\Temp\\pip-req-build-k7j7dxcd\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\xh104\\AppData\\Local\\Temp\\pip-req-build-k7j7dxcd\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\xh104\AppData\Local\Temp\pip-wheel-6_ef07f4'
       cwd: C:\Users\xh104\AppData\Local\Temp\pip-req-build-k7j7dxcd\PythonAPI
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.7\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\pycocotools
  creating build\temp.win-amd64-3.7\common
  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\ProgramData\Anaconda3\envs\ysfish\lib\site-packages\numpy\core\include -I../common -ID:\ProgramData\Anaconda3\envs\ysfish\include -ID:\ProgramData\Anaconda3\envs\ysfish\include "-ID:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-ID:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools/_mask.obj
  _mask.c
  d:\programdata\anaconda3\envs\ysfish\include\pyconfig.h(203): fatal error C1083: 无法打开包括文件: “basetsd.h”: No such file or directory
  error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  ERROR: Command errored out with exit status 1:
   command: 'D:\ProgramData\Anaconda3\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xh104\\AppData\\Local\\Temp\\pip-req-build-k7j7dxcd\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\xh104\\AppData\\Local\\Temp\\pip-req-build-k7j7dxcd\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\xh104\AppData\Local\Temp\pip-req-build-k7j7dxcd
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\xh104\AppData\Local\Temp\pip-req-build-k7j7dxcd\PythonAPI\setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "D:\ProgramData\Anaconda3\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 972, in cythonize
      aliases=aliases)
    File "D:\ProgramData\Anaconda3\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "D:\ProgramData\Anaconda3\envs\ysfish\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
    Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\ProgramData\Anaconda3\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xh104\\AppData\\Local\\Temp\\pip-req-build-k7j7dxcd\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\xh104\\AppData\\Local\\Temp\\pip-req-build-k7j7dxcd\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xh104\AppData\Local\Temp\pip-record-zsd_4k4v\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ProgramData\Anaconda3\envs\ysfish\Include\pycocotools'
         cwd: C:\Users\xh104\AppData\Local\Temp\pip-req-build-k7j7dxcd\PythonAPI
    Complete output (9 lines):
    running install
    running build
    running build_py
    running build_ext
    building 'pycocotools._mask' extension
    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\ProgramData\Anaconda3\envs\ysfish\lib\site-packages\numpy\core\include -I../common -ID:\ProgramData\Anaconda3\envs\ysfish\include -ID:\ProgramData\Anaconda3\envs\ysfish\include "-ID:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-ID:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools/_mask.obj
    _mask.c
    d:\programdata\anaconda3\envs\ysfish\include\pyconfig.h(203): fatal error C1083: 无法打开包括文件: “basetsd.h”: No such file or directory
    error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\ProgramData\Anaconda3\envs\ysfish\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xh104\\AppData\\Local\\Temp\\pip-req-build-k7j7dxcd\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\xh104\\AppData\\Local\\Temp\\pip-req-build-k7j7dxcd\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xh104\AppData\Local\Temp\pip-record-zsd_4k4v\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ProgramData\Anaconda3\envs\ysfish\Include\pycocotools' Check the logs for full command output.
Traceback (most recent call last):
  File "requirements.py", line 72, in <module>
    main()
  File "requirements.py", line 66, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 15, in pip_install
    check=True,
  File "D:\ProgramData\Anaconda3\envs\ysfish\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['D:\\ProgramData\\Anaconda3\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status 1.

**Comment by LawChli** [comment]
楼主怎么解决的？我也有一样的问题
