### ISSUE TITLE
运行的硬件环境

### ISSUE THREAD

**Issue by 1074224619** [7eu7d7/genshin_auto_fish#183]
我按照您的思路,在我自己电脑上运行效果并不好,大概给出一个判定需要200ms左右,所以想问一下您的电脑配置

**Comment by 7eu7d7** [comment]
可以安装CUDA用显卡运行，会快的多

**Comment by 1074224619** [comment]
我的不是训练的时候慢,是运行的时候慢.
我只保留了您的DQN辅助拉杆功能(目标检测功能我删掉了)
辅助拉杆,就是截图,用opencv匹配,然后放到agent决策0,1动作,然后pyautogui模拟鼠标点击,
这一套下来,需要250ms左右才能做出一次动作.
由于一次动作只是点击鼠标一次,所以表现出来就是力度条动弹不得.
我让鼠标长按200ms,又显得比较笨拙,而且效果也不是很好

所以想问一下您展示效果的硬件环境,是什么,让我看看需要啥硬件才能达到流畅的效果.
我觉得只辅助拉杆,应该不用cuda加速把

**Comment by 1074224619** [comment]
> 我的不是训练的时候慢,是运行的时候慢. 我只保留了您的DQN辅助拉杆功能(目标检测功能我删掉了) 辅助拉杆,就是截图,用opencv匹配,然后放到agent决策0,1动作,然后pyautogui模拟鼠标点击, 这一套下来,需要250ms左右才能做出一次动作. 由于一次动作只是点击鼠标一次,所以表现出来就是力度条动弹不得. 我让鼠标长按200ms,又显得比较笨拙,而且效果也不是很好
> 
> 所以想问一下您展示效果的硬件环境,是什么,让我看看需要啥硬件才能达到流畅的效果. 我觉得只辅助拉杆,应该不用cuda加速把

我的不是训练的时候慢,是运行的时候慢.
我只保留了您的DQN辅助拉杆功能(目标检测功能我删掉了)
辅助拉杆,就是截图,用opencv匹配,然后放到agent决策0,1动作,然后pyautogui模拟鼠标点击,
这一套下来,需要250ms左右才能做出一次动作.
由于一次动作只是点击鼠标一次,所以表现出来就是力度条动弹不得.
我让鼠标长按200ms,又显得比较笨拙,而且效果也不是很好

所以想问一下您展示效果的硬件环境,是什么,让我看看需要啥硬件才能达到流畅的效果.
我觉得只辅助拉杆,应该不用cuda加速把

**Comment by 1074224619** [comment]
> 可以安装CUDA用显卡运行，会快的多

我的不是训练的时候慢,是运行的时候慢.
我只保留了您的DQN辅助拉杆功能(目标检测功能我删掉了)
辅助拉杆,就是截图,用opencv匹配,然后放到agent决策0,1动作,然后pyautogui模拟鼠标点击,
这一套下来,需要250ms左右才能做出一次动作.
由于一次动作只是点击鼠标一次,所以表现出来就是力度条动弹不得.
我让鼠标长按200ms,又显得比较笨拙,而且效果也不是很好

所以想问一下您展示效果的硬件环境,是什么,让我看看需要啥硬件才能达到流畅的效果.
我觉得只辅助拉杆,应该不用cuda加速把
