### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by NiuXZi** [7eu7d7/genshin_auto_fish#184]
![image](https://user-images.githubusercontent.com/61132813/143763165-b7fac664-06f7-47b9-b011-55aedb52684b.png)
已安装Python3.7

**Comment by HuYo-OS** [comment]
主要是上面的一条，“import win32api,win32con,win32gui,win32ui”，你可以pip install pywin32试试

**Comment by NiuXZi** [comment]
> 
![image](https://user-images.githubusercontent.com/61132813/143792725-8dea4bbd-5aeb-4b4b-9a86-e30792ac1d2b.png)
试了试，已经安装过了
