### ISSUE TITLE
非1080P分辨率检测不到鱼

### ISSUE THREAD

**Issue by Nxys** [7eu7d7/genshin_auto_fish#186]
3840x1600分辨率，会检测不到鱼，调整恰当位置后，其他目标检测似乎也有问题。

**Comment by NiuXZi** [comment]
我1080p也会检测不到鱼....

**Comment by Nxys** [comment]
经调试，本机问题已找到：cv2.cvtColor 转换code有问题，由cv2.COLOR_RGB2BGR改为cv2.COLOR_RGBA2RGB，就能够检测鱼了。
#185 #181 #174 #112

**Comment by LittleNightmare** [comment]
emmm 我按照Nxys的修改后，ff.do_fish()的抛竿加快了，最后结尾，判断是否钓完鱼的done正常了
