### ISSUE TITLE
YOLOX训练时报错No such file or directory: ../datas/fish_dataset\\annotations\\fish_p2_75+jam.json

### ISSUE THREAD

**Issue by undingable0** [7eu7d7/genshin_auto_fish#19]
大佬大佬，请教一下，我在YOLOX训练时会报错。
提示 【Errno 2】 No such file or directory: ../datas/fish_dataset\\annotations\\fish_p2_75+jam.json

命令是python yolox_tools/train.py -f yolox/exp/yolox_tiny_fish.py -d 1 -b 8 --fp16 -o -c weights/best_tiny3.pth
![image](https://user-images.githubusercontent.com/63138303/134144777-3c8e7606-5d83-43e6-9c2b-c55bb59f6cf8.png)

**Comment by lxzcl** [comment]
同问题，救救孩子，

**Comment by 7eu7d7** [comment]
数据集已经上传，具体看最新的训练说明
