### ISSUE TITLE
提示没有best_tiny3.pth 这个文件，预训练权重 (.pth文件)名字不是 yolox_tiny.pth 吗？

### ISSUE THREAD

**Issue by zhaoxishm** [7eu7d7/genshin_auto_fish#199]
运行后报错
FileNotFoundError: [Errno 2] No such file or directory: 'weights/best_tiny3.pth'
![233](https://user-images.githubusercontent.com/14160172/146537893-bee55dfb-485d-4036-b41a-52a5d7b5251b.png)

**Comment by memory009** [comment]
这个是要自己下载的  作者放在github里面了

**Comment by oukarvc** [comment]
我运行后也是这样，有解决办法了吗

**Comment by zhaoxishm** [comment]
去QQ群779324188下载&nbsp; 原神钓鱼脚本吧，弄这个太麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "7eu7d7/genshin_auto_fish"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [7eu7d7/genshin_auto_fish] 提示没有best_tiny3.pth 这个文件，预训练权重 (.pth文件)名字不是 yolox_tiny.pth 吗？ (Issue #199)





 
我运行后也是这样，有解决办法了吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by artangnis** [comment]
> 这个是要自己下载的 作者放在github里面了 https://github.com/7eu7d7/genshin_auto_fish/tree/weights

这个链接里没有是怎么回事
