### ISSUE TITLE
Script file 'D:\Anaconda3\envs\ysfish\Scripts\pip-script.py' is not present.

### ISSUE THREAD

**Issue by Oskrrrr** [7eu7d7/genshin_auto_fish#2]
![1](https://user-images.githubusercontent.com/68583635/134103527-54003e11-d02d-4b4e-8314-dc4cdf5b13b3.png)

**Comment by AwakeAE** [comment]
应该是anaconda配置的问题

**Comment by Oskrrrr** [comment]
这个怎么解决啊┭┮﹏┭┮

**Comment by AwakeAE** [comment]
试试看在conda在的路径里，\Anaconda3右击属性->安全->user选中现在的用户，修改权限至所有权限。之后重新打开命令行

**Comment by Oskrrrr** [comment]
还是。。不太行

**Comment by 7eu7d7** [comment]
可以参考这个教程https://blog.csdn.net/weixin_41010198/article/details/107174343

**Comment by Oskrrrr** [comment]
还是有点问题
![2](https://user-images.githubusercontent.com/68583635/134113292-f0c5acbb-532b-49be-9335-3f508ddd6c7b.png)

**Comment by 7eu7d7** [comment]
> 还是有点问题
> ![2](https://user-images.githubusercontent.com/68583635/134113292-f0c5acbb-532b-49be-9335-3f508ddd6c7b.png)

重新clone最新版代码试试

**Comment by Popcorkent** [comment]
解决了吗，我也是这个问题

**Comment by inory121** [comment]
重新创建anaconda环境，不要升级pip（不要运行这个pip install -U pip）

**Comment by lie5860** [comment]
是不是开了代理了。

**Comment by cxs-fight** [comment]
conda install -f pip      强制安装pip
