### ISSUE TITLE
装torch的时候报错了

### ISSUE THREAD

**Issue by nightlye** [7eu7d7/genshin_auto_fish#211]
![image](https://user-images.githubusercontent.com/53067795/147819670-b9cb30be-93f8-4175-a3ab-958e0f59cb01.png)
但我去官网用他那个pip命令装，换源到清华、豆瓣，都装不上
python版本3.6的，直接用的anaconda里的版本

**Comment by HuYo-OS** [comment]
这个问题就很玄学，错误的意思是所选的源内没有版本为1.7.0+cpu的torch；
你尝试更换其他版本的torch来进行安装

**Comment by nightlye** [comment]
我重装anaconda后又报新的错误了
![image](https://user-images.githubusercontent.com/53067795/147842925-32abd12c-44b1-4a65-bebe-f50266b43da9.png)

**Comment by nightlye** [comment]
不过torch装好了

**Comment by nightlye** [comment]
我多试几次命令，这个就装好了，，，挺玄学的
