### ISSUE TITLE
各位，为什么我的不会连续钓啊，求助！

### ISSUE THREAD

**Issue by zzbjyhy** [7eu7d7/genshin_auto_fish#221]
钓上一条没问题，但是不会连续钓，中间要隔很久

**Comment by wza123** [comment]
同问

**Comment by sandboxdream** [comment]
我分步骤测试发现是一直在和鱼较量的循环中未退出。
我的解决方式是在fishing.py的186行后增加
`            if not(env.is_bite()):
                winsound.Beep(1500, 1000)
                break`

**Comment by zzbjyhy** [comment]
> 我分步骤测试发现是一直在和鱼较量的循环中未退出。我的解决方式是在 fishing.py 的186行后增加
> 
> ```
>             if not(env.is_bite()):
>                 winsound.Beep(1500, 1000)
>                 break
> ```
请问实在if内嵌套这个if吗

**Comment by zzbjyhy** [comment]
请问是在if中嵌套一个if吗？ @ @sandboxdream

**Comment by sandboxdream** [comment]
不是，这两个if应该是并列关系@zzbjyhy

**Comment by zzbjyhy** [comment]
> 我分步骤测试发现是一直在和鱼较量的循环中未退出。 我的解决方式是在fishing.py的186行后增加
> 
> ```
>             if not(env.is_bite()):
>                 winsound.Beep(1500, 1000)
>                 break
> ```

这个办法亲测有效

**Comment by wza123** [comment]
感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月18日(星期二) 下午5:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [7eu7d7/genshin_auto_fish] 各位，为什么我的不会连续钓啊，求助！ (Issue #221)





  
我分步骤测试发现是一直在和鱼较量的循环中未退出。 我的解决方式是在fishing.py的186行后增加
             if not(env.is_bite()):                 winsound.Beep(1500, 1000)                 break   
这个办法亲测有效
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
