### ISSUE TITLE
问下，安装requirement.py的时候一直会报错

### ISSUE THREAD

**Issue by pockyliu** [7eu7d7/genshin_auto_fish#223]
Requirement already satisfied: dataclasses in e:\anaconda\envs\ysfish\lib\site-packages (from torch==1.7.0+cpu) (0.6)
Requirement already satisfied: future in e:\anaconda\envs\ysfish\lib\site-packages (from torch==1.7.0+cpu) (0.18.2)
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Requirement already satisfied: torchvision==0.8.1+cpu in e:\anaconda\envs\ysfish\lib\site-packages (0.8.1+cpu)
Requirement already satisfied: thop in e:\anaconda\envs\ysfish\lib\site-packages (0.0.31.post2005241907)
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\pocky\appdata\local\temp\pip-req-build-dpk72k2a
  Running command git clone --filter=blob:none -q https://github.com/philferriere/cocoapi.git 'C:\Users\pocky\AppData\Local\Temp\pip-req-build-dpk72k2a'
  fatal: unable to access 'https://github.com/philferriere/cocoapi.git/': OpenSSL SSL_read: Connection was aborted, errno 10053
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

WARNING: Discarding git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI. Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/philferriere/cocoapi.git 'C:\Users\pocky\AppData\Local\Temp\pip-req-build-dpk72k2a' Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/philferriere/cocoapi.git 'C:\Users\pocky\AppData\Local\Temp\pip-req-build-dpk72k2a' Check the logs for full command output.
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 13, in pip_install
    subprocess.run(
  File "E:\anaconda\envs\ysfish\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['E:\\anaconda\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status 1

**Comment by futuer-szd** [comment]
可能是github太慢了，coco我也下不成功，多试几次

**Comment by pockyliu** [comment]
试了好多次诶。。科学上网了也不行。。我直接git clone是可以下下来的。。

**Comment by AlaskaZ-V** [comment]
把torch版本换成1.8,1.7只支持py3.8以下
