### ISSUE TITLE
yolox训练报错

### ISSUE THREAD

**Issue by D3caRab1an** [7eu7d7/genshin_auto_fish#23]
yolox在训练时会跳出AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
![image](https://user-images.githubusercontent.com/91132226/134169456-fc6e28b8-3494-4d25-bfd9-ced9218779b0.png)

**Comment by 7eu7d7** [comment]
训练需要使用CUDA加速，可能装的是cpu版

**Comment by MaxwellYe0815** [comment]
> 训练需要使用CUDA加速，可能装的是cpu版

必须使用cuda加速吗，amd显卡无法安装cuda

**Comment by 7eu7d7** [comment]
> > 训练需要使用CUDA加速，可能装的是cpu版
> 
> 必须使用cuda加速吗，amd显卡无法安装cuda

pytorch1.8以后也支持AMD了，但配置很麻烦，不是专业做这些的可能配起来比较费劲。
