### ISSUE TITLE
执行python setup.py develop时报错

### ISSUE THREAD

**Issue by WYXsb** [7eu7d7/genshin_auto_fish#230]
![QQ图片20220131172337](https://user-images.githubusercontent.com/62527555/151768531-bfc101f6-7a54-4471-9453-7346a63bb407.png)
大佬帮忙看看这个问题是怎么了呀，我装了ninja的。

**Comment by WYXsb** [comment]
找到错误了，原来是我没改环境变量

**Comment by WYXsb** [comment]
![image](https://user-images.githubusercontent.com/62527555/151774563-1552dbbb-12e4-426a-a7ac-cbf3a8f94a7a.png)
安装yolox时，又遇到了新的错误

**Comment by HuYo-OS** [comment]
NumPy版本？你可以升级一下NumPy版本，实在不行可以更换下Python版本，本人使用的是python 3.7

**Comment by HuYo-OS** [comment]
也可以联系我，可以远程帮你配置

**Comment by WYXsb** [comment]
> NumPy版本？你可以升级一下NumPy版本，实在不行可以更换下Python版本，本人使用的是python 3.7
都试过了，还是不行，一样的错误

**Comment by WYXsb** [comment]
numpy也升级了，python版本也换了，还是报一样的错误

**Comment by WYXsb** [comment]
@HuYo-OS ，大佬，numpy版本也升级了，也换了python3.7还是一样的错。

**Comment by HuYo-OS** [comment]
> @HuYo-OS ，大佬，numpy版本也升级了，也换了python3.7还是一样的错。

把现有环境删除，重新配置

**Comment by WYXsb** [comment]
> > @HuYo-OS ，大佬，numpy版本也升级了，也换了python3.7还是一样的错。
> 
> 把现有环境删除，重新配置
重新配置时，那个git的命令老出错，我自己git clone下来安装了pycocotools还是报这个错。

**Comment by WYXsb** [comment]
又配置了一遍，requirements.py执行成功，但还是报老错。

**Comment by HuYo-OS** [comment]
> 又配置了一遍，requirements.py 执行成功，但还是报老错。

啊这，我自己配置就没问题

**Comment by HuYo-OS** [comment]
你可以参考一下我的超长截图，正常安装应该是这样的
![2022-02-05_110118](https://user-images.githubusercontent.com/94115384/152626589-1cdfaf26-446c-4169-abd8-d92a123a8f7a.png)

**Comment by Allbooo** [comment]
可以加下好友么，我也遇到文件缺失步骤但一步步按操作来的不知道为什么提示没有pip-script.py。VX：18704536081

**Comment by HuYo-OS** [comment]
> 可以加下好友么，我也遇到文件缺失步骤但一步步按操作来的不知道为什么提示没有 pip-script.py。VX：18704536081

嗯嗯
