### ISSUE TITLE
Building wheel for pycocotools (setup.py) ... error

### ISSUE THREAD

**Issue by windskyxb** [7eu7d7/genshin_auto_fish#234]
![image](https://user-images.githubusercontent.com/60282327/152915064-70e5ca50-eb8d-43a0-aa32-054998f83c71.png)

![image](https://user-images.githubusercontent.com/60282327/152915106-b6d2aad4-ddbf-4387-8f3a-f1c37c47b355.png)

**Comment by HuYo-OS** [comment]
装vs了吗（Microsoft Visual Studio）

**Comment by windskyxb** [comment]
> 装vs了吗（Microsoft Visual Studio）

谢谢，装了vs之后正常运行了
