### ISSUE TITLE
运行python requirements.py报错，

### ISSUE THREAD

**Issue by SSSanSui** [7eu7d7/genshin_auto_fish#236]
(ysfish) D:\Users\Administrator\Desktop\原神辅助\钓鱼\genshin_auto_fish>python requirements.py
Requirement already satisfied: cython in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.29.27)
Requirement already satisfied: scikit-image in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.15.0)
Requirement already satisfied: imageio>=2.0.1 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (2.15.0)
Requirement already satisfied: pillow>=4.3.0 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (8.4.0)
Requirement already satisfied: networkx>=2.0 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (2.5.1)
Requirement already satisfied: PyWavelets>=0.4.0 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (1.1.1)
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from imageio>=2.0.1->scikit-image) (1.19.5)
Requirement already satisfied: decorator<5,>=4.3 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from networkx>=2.0->scikit-image) (4.4.2)
Requirement already satisfied: loguru in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.6.0)
Requirement already satisfied: colorama>=0.3.4 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from loguru) (0.4.4)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from loguru) (1.1.0)
Requirement already satisfied: aiocontextvars>=0.2.0 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from loguru) (0.2.2)
Requirement already satisfied: contextvars==2.4 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from aiocontextvars>=0.2.0->loguru) (2.4)
Requirement already satisfied: immutables>=0.9 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from contextvars==2.4->aiocontextvars>=0.2.0->loguru) (0.16)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from immutables>=0.9->contextvars==2.4->aiocontextvars>=0.2.0->loguru) (4.0.1)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (3.3.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (3.0.7)
Requirement already satisfied: numpy>=1.15 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (1.19.5)
Requirement already satisfied: python-dateutil>=2.1 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (8.4.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from python-dateutil>=2.1->matplotlib) (1.16.0)
Requirement already satisfied: tabulate in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.8.9)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (4.62.3)
Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from tqdm) (0.4.4)
Requirement already satisfied: pywin32 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (303)
Requirement already satisfied: PyAutoGUI in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.9.53)
Requirement already satisfied: mouseinfo in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (0.1.3)
Requirement already satisfied: PyTweening>=1.0.1 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (1.0.4)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (0.1.28)
Requirement already satisfied: pymsgbox in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (1.0.9)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (0.0.9)
Requirement already satisfied: pyrect in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from pygetwindow>=0.0.5->PyAutoGUI) (0.1.4)
Requirement already satisfied: Pillow>=4.0.0 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from pyscreeze>=0.1.21->PyAutoGUI) (8.4.0)
Requirement already satisfied: pyperclip in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from mouseinfo->PyAutoGUI) (1.8.2)
Requirement already satisfied: PyYAML>=5.3.1 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (6.0)
Requirement already satisfied: opencv_python in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (4.5.5.62)
Requirement already satisfied: numpy>=1.13.3 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from opencv_python) (1.19.5)
Requirement already satisfied: keyboard in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.13.5)
Requirement already satisfied: Pillow in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (8.4.0)
Requirement already satisfied: pymouse in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (1.0)
Requirement already satisfied: numpy==1.19.5 in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (1.19.5)
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Requirement already satisfied: torch==1.7.0+cpu in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (1.7.0+cpu)
Requirement already satisfied: dataclasses in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from torch==1.7.0+cpu) (0.8)
Requirement already satisfied: future in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from torch==1.7.0+cpu) (0.18.2)
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from torch==1.7.0+cpu) (1.19.5)
Requirement already satisfied: typing-extensions in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from torch==1.7.0+cpu) (4.0.1)
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Requirement already satisfied: torchvision==0.8.1+cpu in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.8.1+cpu)
Requirement already satisfied: thop in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.0.31.post2005241907)
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to d:\users\admini~1\appdata\local\temp\pip-req-build-0_eep9jb
  Running command git clone --filter=blob:none -q https://github.com/philferriere/cocoapi.git 'D:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-0_eep9jb'
  fatal: unable to access 'https://github.com/philferriere/cocoapi.git/': Failed to connect to github.com port 443 after 21045 ms: Timed out
WARNING: Discarding git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI. Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/philferriere/cocoapi.git 'D:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-0_eep9jb' Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/philferriere/cocoapi.git 'D:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-0_eep9jb' Check the logs for full command output.
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 16, in pip_install
    check=True,
  File "C:\ProgramData\Anaconda3\envs\ysfish\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status 1.

**Comment by T0n0T** [comment]
连接超时了吧，网络问题

**Comment by cbntrt** [comment]
在 https://download.pytorch.org/whl/torch_stable.html 下载轮子包，然后本地安装就可以了
