### ISSUE TITLE
运行 python requirements.py时报错

### ISSUE THREAD

**Issue by yuiandui** [7eu7d7/genshin_auto_fish#240]
大佬们，请问这该怎么解决？
Looking in links: https://download.pytorch.org/whl/torch_stable.html
warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://download.pytorch.org/whl/torch_stable.html

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cpu (from versions: 1.7.1, 1.7.1+cpu, 1.7.1+cu101, 1.7.1+cu110, 1.8.0, 1.8.0+cpu, 1.8.0+cu101, 1.8.0+cu111, 1.8.1, 1.8.1+cpu, 1.8.1+cu101, 1.8.1+cu102, 1.8.1+cu111, 1.9.0, 1.9.0+cpu, 1.9.0+cu102, 1.9.0+cu111, 1.9.1, 1.9.1+cpu, 1.9.1+cu102, 1.9.1+cu111, 1.10.0, 1.10.0+cpu, 1.10.0+cu102, 1.10.0+cu111, 1.10.0+cu113, 1.10.1, 1.10.1+cpu, 1.10.1+cu102, 1.10.1+cu111, 1.10.1+cu113, 1.10.2, 1.10.2+cpu, 1.10.2+cu102, 1.10.2+cu111, 1.10.2+cu113)
ERROR: No matching distribution found for torch==1.7.0+cpu
Traceback (most recent call last):
  File "E:\genshin_auto_fish-master\requirements.py", line 74, in <module>
    main()
  File "E:\genshin_auto_fish-master\requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "E:\genshin_auto_fish-master\requirements.py", line 13, in pip_install
    subprocess.run(
  File "E:\anaconda\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['E:\\anaconda\\python.exe', '-m', 'pip', 'install', 'torch==1.7.0+cpu', '-f', 'https://download.pytorch.org/whl/torch_stable.html']' returned non-zero exit status 1.

**Comment by 7eu7d7** [comment]
更新了一下安装脚本，安装1.8.2 LTS的比较好
