### ISSUE TITLE
requirements.py出错，不支持cu116

### ISSUE THREAD

**Issue by Michael-Rin** [7eu7d7/genshin_auto_fish#247]
显示最高支持到1.8.2+cu111，但是cuda版本是11.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.16.1 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.
Successfully installed numpy-1.19.5
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
ERROR: Could not find a version that satisfies the requirement torch==1.8.2+cu116 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.8.1+cpu, 1.8.1+cu102, 1.8.1+cu111, 1.8.2+cpu, 1.8.2+cu101, 1.8.2+cu102, 1.8.2+cu111, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2)
ERROR: No matching distribution found for torch==1.8.2+cu116

**Comment by HuYo-OS** [comment]
你可以安装1.10.2
pip3 install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio===0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
这个是官网链接

**Comment by Michael-Rin** [comment]
下载好113的包之后，不使用本地代理还报1.8.2+cu113错误
使用本地代理之后显示的是
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000128211D8C70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))': /simple/scikit-image/

**Comment by Michael-Rin** [comment]
(ysfish) C:\Users\Michael Rin\genshin_auto_fish>python requirements.py --cuda 113
Requirement already satisfied: cython in d:\anaconda3\envs\ysfish\lib\site-packages (0.29.28)
Requirement already satisfied: scikit-image in d:\anaconda3\envs\ysfish\lib\site-packages (0.19.2)
Requirement already satisfied: networkx>=2.2 in d:\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (2.7.1)
Requirement already satisfied: scipy>=1.4.1 in d:\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (1.8.0)
Requirement already satisfied: tifffile>=2019.7.26 in d:\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (2022.2.9)
Requirement already satisfied: packaging>=20.0 in d:\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (21.3)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in d:\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (9.0.1)
Requirement already satisfied: imageio>=2.4.1 in d:\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (2.16.1)
Requirement already satisfied: PyWavelets>=1.1.1 in d:\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (1.2.0)
Requirement already satisfied: numpy>=1.17.0 in d:\anaconda3\envs\ysfish\lib\site-packages (from scikit-image) (1.19.5)
Collecting numpy>=1.17.0
  Using cached numpy-1.22.3-cp38-cp38-win_amd64.whl (14.7 MB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in d:\anaconda3\envs\ysfish\lib\site-packages (from packaging>=20.0->scikit-image) (3.0.7)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
Successfully installed numpy-1.22.3
Requirement already satisfied: loguru in d:\anaconda3\envs\ysfish\lib\site-packages (0.6.0)
Requirement already satisfied: win32-setctime>=1.0.0 in d:\anaconda3\envs\ysfish\lib\site-packages (from loguru) (1.1.0)
Requirement already satisfied: colorama>=0.3.4 in d:\anaconda3\envs\ysfish\lib\site-packages (from loguru) (0.4.4)
Requirement already satisfied: matplotlib in d:\anaconda3\envs\ysfish\lib\site-packages (3.5.1)
Requirement already satisfied: cycler>=0.10 in d:\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in d:\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (9.0.1)
Requirement already satisfied: packaging>=20.0 in d:\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (21.3)
Requirement already satisfied: numpy>=1.17 in d:\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (1.22.3)
Requirement already satisfied: pyparsing>=2.2.1 in d:\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (3.0.7)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (4.29.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\anaconda3\envs\ysfish\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: six>=1.5 in d:\anaconda3\envs\ysfish\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: tabulate in d:\anaconda3\envs\ysfish\lib\site-packages (0.8.9)
Requirement already satisfied: tqdm in d:\anaconda3\envs\ysfish\lib\site-packages (4.63.0)
Requirement already satisfied: colorama in d:\anaconda3\envs\ysfish\lib\site-packages (from tqdm) (0.4.4)
Requirement already satisfied: pywin32 in d:\anaconda3\envs\ysfish\lib\site-packages (303)
Requirement already satisfied: PyAutoGUI in d:\anaconda3\envs\ysfish\lib\site-packages (0.9.53)
Requirement already satisfied: pygetwindow>=0.0.5 in d:\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (0.0.9)
Requirement already satisfied: mouseinfo in d:\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (0.1.3)
Requirement already satisfied: PyTweening>=1.0.1 in d:\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (1.0.4)
Requirement already satisfied: pyscreeze>=0.1.21 in d:\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (0.1.28)
Requirement already satisfied: pymsgbox in d:\anaconda3\envs\ysfish\lib\site-packages (from PyAutoGUI) (1.0.9)
Requirement already satisfied: pyrect in d:\anaconda3\envs\ysfish\lib\site-packages (from pygetwindow>=0.0.5->PyAutoGUI) (0.1.4)
Requirement already satisfied: Pillow>=6.2.1 in d:\anaconda3\envs\ysfish\lib\site-packages (from pyscreeze>=0.1.21->PyAutoGUI) (9.0.1)
Requirement already satisfied: pyperclip in d:\anaconda3\envs\ysfish\lib\site-packages (from mouseinfo->PyAutoGUI) (1.8.2)
Requirement already satisfied: PyYAML>=5.3.1 in d:\anaconda3\envs\ysfish\lib\site-packages (6.0)
Requirement already satisfied: opencv_python in d:\anaconda3\envs\ysfish\lib\site-packages (4.5.5.64)
Requirement already satisfied: numpy>=1.17.3 in d:\anaconda3\envs\ysfish\lib\site-packages (from opencv_python) (1.22.3)
Requirement already satisfied: keyboard in d:\anaconda3\envs\ysfish\lib\site-packages (0.13.5)
Requirement already satisfied: Pillow in d:\anaconda3\envs\ysfish\lib\site-packages (9.0.1)
Requirement already satisfied: pymouse in d:\anaconda3\envs\ysfish\lib\site-packages (1.0)
Collecting numpy==1.19.5
  Using cached numpy-1.19.5-cp38-cp38-win_amd64.whl (13.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.3
    Uninstalling numpy-1.22.3:
      Successfully uninstalled numpy-1.22.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.16.1 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.
Successfully installed numpy-1.19.5
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
ERROR: Could not find a version that satisfies the requirement torch==1.8.2+cu113 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.8.1+cpu, 1.8.1+cu102, 1.8.1+cu111, 1.8.2+cpu, 1.8.2+cu101, 1.8.2+cu102, 1.8.2+cu111, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2)
ERROR: No matching distribution found for torch==1.8.2+cu113
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 13, in pip_install
    subprocess.run(
  File "D:\anaconda3\envs\ysfish\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\anaconda3\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', 'torch==1.8.2+cu113', '-f', 'https://download.pytorch.org/whl/lts/1.8/torch_lts.html']' returned non-zero exit status 1.

**Comment by Michael-Rin** [comment]
在requirements.py里面修改torch的版本和源，我甚至装上了torch1.11.0+cu115、torchvision0.12.1+cu115
