### ISSUE TITLE
must give at least one requirement to install (see "pip help install")

### ISSUE THREAD

**Issue by pianfanshaan** [7eu7d7/genshin_auto_fish#27]
![image](https://user-images.githubusercontent.com/49159625/134193789-1a7233f2-0168-4922-93a8-a419609ecc06.png)

![image](https://user-images.githubusercontent.com/49159625/134194280-e57be637-6ed6-4195-80ee-4e676eebccf6.png)

**Comment by xz304776** [comment]
遇到了同样的问题

**Comment by lxzcl** [comment]
github连接问题，pip没有目标，没能从github下载到需要的文件导致

**Comment by pianfanshaan** [comment]
> github连接问题，pip没有目标，没能从github下载到需要的文件导致

但科学上网也无法下载 科学上网网速不是很差...

**Comment by lxzcl** [comment]
> > github连接问题，pip没有目标，没能从github下载到需要的文件导致
> 
> 但科学上网也无法下载 科学上网速不是很差...

我也尝试科学上网但是在这个应用内会出现http报错，代理端口的问题，在这个软件上要特殊的设置，你确定你设置了么？

**Comment by inory121** [comment]
git设置一下就行了
git config --global http.sslVerify false

**Comment by pianfanshaan** [comment]
> > > github连接问题，pip没有目标，没能从github下载到需要的文件导致
> > 
> > 
> > 但科学上网也无法下载 科学上网速不是很差...
> 
> 我也尝试科学上网但是在这个应用内会出现http报错，代理端口的问题，在这个软件上要特殊的设置，你确定你设置了么？

请问是要什么样的特殊设置呢

**Comment by xuzhougeng** [comment]
@pianfanshaan 可以考虑用github的镜像 https://doc.fastgit.org/zh-cn/guide.html

**Comment by lxzcl** [comment]
> > > > github连接问题，pip没有目标，没能从github下载到需要的文件导致
> > > 
> > > 
> > > 但科学上网也无法下载 科学上网速不是很差...
> > 
> > 
> > 我也尝试科学上网但是在这个应用内会出现http报错，代理端口的问题，在这个软件上要特殊的设置，你确定你设置了么？
> 
> 请问是要什么样的特殊设置呢

我也没有设置过，但是在搜索引擎上有相关设置教程，我的是关掉科学上网多尝试几次就连上了，或许你可以试试手机的数据。
或者参考 @xuzhougeng 的这条https://github.com/7eu7d7/genshin_auto_fish/issues/27#issuecomment-924518628建议

**Comment by pianfanshaan** [comment]
> @pianfanshaan 可以考虑用github的镜像 https://doc.fastgit.org/zh-cn/guide.html

还是不行 我把git配置改了也是原来的样子

**Comment by pianfanshaan** [comment]
> git设置一下就行了
> git config --global http.sslVerify false

还是失败了

**Comment by 7eu7d7** [comment]
这个已经安装好了，可能是安装命令里有空行，没其他错可以不用管
