### ISSUE TITLE
加入fish数据集后YOLOX训练报错

### ISSUE THREAD

**Issue by lxzcl** [7eu7d7/genshin_auto_fish#28]
![image](https://user-images.githubusercontent.com/41499707/134197681-59c7b409-0ac2-4afa-afab-286bfeb49599.png)
![image](https://user-images.githubusercontent.com/41499707/134197734-2febaf64-e3f3-4cb7-9456-6b4278783aae.png)
请问这个报错是正常的么？

**Comment by pianfanshaan** [comment]
你有没有下载鱼群数据集

**Comment by lxzcl** [comment]
> 你有没有下载鱼群数据集

不我下载了，仔细看报错，报错也并没有显示是文件问题，我也检查过路径设置确实没问题，显存也上去过一段时间，
![image](https://user-images.githubusercontent.com/41499707/134211551-58452b01-40da-4476-8e8f-d6c93da8332f.png)
![image](https://user-images.githubusercontent.com/41499707/134211627-5feec556-0b8e-436c-baa5-e97afc3bf35a.png)
我尝试截图，弹出新错误，说我显存不够，离谱

**Comment by lxzcl** [comment]
有什么解决方法么？

**Comment by pianfanshaan** [comment]
> > 你有没有下载鱼群数据集
> 
> 不我下载了，仔细看报错，报错也并没有显示是文件问题，我也检查过路径设置确实没问题，显存也上去过一段时间，
> ![image](https://user-images.githubusercontent.com/41499707/134211551-58452b01-40da-4476-8e8f-d6c93da8332f.png)
> ![image](https://user-images.githubusercontent.com/41499707/134211627-5feec556-0b8e-436c-baa5-e97afc3bf35a.png)
> 我尝试截图，弹出新错误，说我显存不够，离谱

想问一下 之前的requirement你有报错吗

**Comment by lxzcl** [comment]
> > > 你有没有下载鱼群数据集
> > 
> > 
> > 不我下载了，仔细看报错，报错也并没有显示是文件问题，我也检查过路径设置确实没问题，显存也上去过一段时间，
> > ![image](https://user-images.githubusercontent.com/41499707/134211551-58452b01-40da-4476-8e8f-d6c93da8332f.png)
> > ![image](https://user-images.githubusercontent.com/41499707/134211627-5feec556-0b8e-436c-baa5-e97afc3bf35a.png)
> > 我尝试截图，弹出新错误，说我显存不够，离谱
> 
> 想问一下 之前的requirement你有报错吗

没有，或许我遇到了，但是忘了，你可以尝试上传你的问题描述

**Comment by pianfanshaan** [comment]
> > > > 你有没有下载鱼群数据集
> > > 
> > > 
> > > 不我下载了，仔细看报错，报错也并没有显示是文件问题，我也检查过路径设置确实没问题，显存也上去过一段时间，
> > > ![image](https://user-images.githubusercontent.com/41499707/134211551-58452b01-40da-4476-8e8f-d6c93da8332f.png)
> > > ![image](https://user-images.githubusercontent.com/41499707/134211627-5feec556-0b8e-436c-baa5-e97afc3bf35a.png)
> > > 我尝试截图，弹出新错误，说我显存不够，离谱
> > 
> > 
> > 想问一下 之前的requirement你有报错吗
> 
> 没有，或许我遇到了，但是忘了，你可以尝试上传你的问题描述

我已经在issue上传了 你可以试试把batch-size改一改

**Comment by lxzcl** [comment]
问题已经解决，我的是笔记本拔掉雷电接口

> > > > > 你有没有下载鱼群数据集
> > > > 
> > > > 
> > > > 不我下载了，仔细看报错，报错也并没有显示是文件问题，我也检查过路径设置确实没问题，显存也上去过一段时间，
> > > > ![image](https://user-images.githubusercontent.com/41499707/134211551-58452b01-40da-4476-8e8f-d6c93da8332f.png)
> > > > ![image](https://user-images.githubusercontent.com/41499707/134211627-5feec556-0b8e-436c-baa5-e97afc3bf35a.png)
> > > > 我尝试截图，弹出新错误，说我显存不够，离谱
> > > 
> > > 
> > > 想问一下 之前的requirement你有报错吗
> > 
> > 
> > 没有，或许我遇到了，但是忘了，你可以尝试上传你的问题描述
> 
> 我已经在issue上传了 你可以试试把batch-size改一改

不好意思我的github很少使用，但是我的问题已经解决，batch-size是什么？我的是笔记本拔掉雷电接口的显示器就解决了！
中间还遇到了个问题RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
解决方法降低numpy版本：
`pip install -U numpy==1.17.0 -i https://pypi.tuna.tsinghua.edu.cn/simple`

**Comment by xuzhougeng** [comment]
@lxzcl  batch-size是每次训练的数据量大小，单次读取的图片越多，占的显存越多。 你的报错是CUDA out of memory，也就是显存爆了。 你的GPU只有4.00 Gib, 其中显示器又占了一部分，所以显内就更加吃紧了。

**Comment by lxzcl** [comment]
> @lxzcl batch-size是每次训练的数据量大小，单次读取的图片越多，占的显存越多。 你的报错是CUDA out of memory，也就是显存爆了。 你的GPU只有4.00 Gib, 其中显示器又占了一部分，所以显内就更加吃紧了。

感谢你的回复，对python的人工智能我也才刚接触

**Comment by pianfanshaan** [comment]
> ize是每次训练的数据量大小，单次读取的图片越多，占的显存越多。 你的报错是CUDA out of memory，也就是显存爆了。 你的GPU只有4.00 Gib, 其中显示器又占了一部分，所以显内就更

请问有什么解决方法吗 我的内存是够的 但是没法分配
