### ISSUE TITLE
請問這是少做哪一步嗎

### ISSUE THREAD

**Issue by hsieheting** [7eu7d7/genshin_auto_fish#283]
前面的步驟應該都有安裝並且成功，但在執行fishing.py時報了這個錯，請問該怎麼解決
![image](https://user-images.githubusercontent.com/87523865/168303907-896670e8-e877-4b03-bd48-1f7a49f87713.png)

**Comment by DarkPocket** [comment]
`python requirements.py`  or  
`python -m pip install -U loguru`

**Comment by EricSell** [comment]
没有进入虚拟环境吧` conda activate ysfish`
