### ISSUE TITLE
推荐使用pyWinHook或pywin32替换停止维护的pyHook

### ISSUE THREAD

**Issue by yxtj** [7eu7d7/genshin_auto_fish#29]
根据官方介绍，pyHook早已经停止维护，pyWinHook是它的一个fork，并且有后续维护。
但是pyWinHook也只维护到python 3.8版本。
我刚刚读了代码，发现environment里面并没有用到太多复杂的hook，完全可以考虑使用pywin32这个基础包代替pyHook。

**Comment by 7eu7d7** [comment]
删掉pyHook了，这样配置起来会方便很多
