### ISSUE TITLE
MainProcess 中的运行错误，是不是torch版本不对

### ISSUE THREAD

**Issue by Yaoyuan-Zhang319** [7eu7d7/genshin_auto_fish#290]
![9D(ZK97@DUKEZQ55J{S P}H](https://user-images.githubusercontent.com/55748015/178113836-936d4b54-ab1c-43ea-8bfe-df5fa335956c.png)

**Comment by shijia0423** [comment]
我也是这个错误，兄弟有解决办法了吗？

**Comment by 7eu7d7** [comment]
你的pytorch是CPU版本的，如果要训练需要下载GPU版本，只是使用不需要训练
