### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by Dreamyc** [7eu7d7/genshin_auto_fish#292]
Requirement already satisfied: typing-extensions in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from torch==1.8.2+cpu) (4.3.0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (from torch==1.8.2+cpu) (1.19.5)
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Requirement already satisfied: torchvision==0.9.2+cpu in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.9.2+cpu)
Requirement already satisfied: thop in c:\programdata\anaconda3\envs\ysfish\lib\site-packages (0.1.1.post2207130030)
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\administrator\appdata\local\temp\pip-req-build-gbyjp7qv
  Running command git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-gbyjp7qv'
  error: RPC failed; curl 28 OpenSSL SSL_read: Connection was reset, errno 10054
  fatal: expected flush after ref listing
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-gbyjp7qv' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-gbyjp7qv' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "requirements.py", line 74, in <module>
    main()
  File "requirements.py", line 68, in main
    pip_install(args.proxy, line.split())
  File "requirements.py", line 19, in pip_install
    subprocess.run(
  File "C:\ProgramData\Anaconda3\envs\ysfish\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\envs\\ysfish\\python.exe', '-m', 'pip', 'install', '--proxy=http://127.0.0.1:10809', 'git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI']' returned non-zero exit status 1.

(ysfish) C:\genshin_auto_fish>git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-gbyjp7qv
fatal: could not create leading directories of ''C:\Users\Administrator\AppData\Local\Temp\pip-req-build-gbyjp7qv': Invalid argument

**Comment by Wu-Yanjiang** [comment]
conda控制台直接运行：pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI进行安装，安装成功后不再python requirements.py，直接运行
