### ISSUE TITLE
报错信息File "fishing.py", line 18, in <module>

### ISSUE THREAD

**Issue by xz304776** [7eu7d7/genshin_auto_fish#31]
![QQ截图20210922020113](https://user-images.githubusercontent.com/77931226/134223606-8ad8554b-6154-4c31-8865-bb9c1cb2cbea.png)

**Comment by inory121** [comment]
![QQ截图20210922094853](https://user-images.githubusercontent.com/35392664/134270714-9bcc33dc-3bf3-47ad-bb5f-c8f493c608c1.png)
仔细查看README

**Comment by xz304776** [comment]
> ![QQ截图20210922094853](https://user-images.githubusercontent.com/35392664/134270714-9bcc33dc-3bf3-47ad-bb5f-c8f493c608c1.png)
> 仔细查看README

我当然有读过，也试过，然而报错信息没有变化
