### ISSUE TITLE
CUDA分配内存失败

### ISSUE THREAD

**Issue by pianfanshaan** [7eu7d7/genshin_auto_fish#32]
设置了batch-size = 2仍旧无法分配
![image](https://user-images.githubusercontent.com/49159625/134273650-e572e667-bd3e-4c0f-b5ff-3fa8bc3d3831.png)
请问cuda是分配内存还是显存?应该是显存吧
1050ti显存记得是4G 但是batch-size已经设置为2仍无法分配 请问应该如何修改?

**Comment by lxzcl** [comment]
4G够的，前提是没有任何占用，可以试试使用核显接口连接显示器，或者想办法把显存内东西清理掉，不过作者提供的数据包学习后改进不大，我也不知道把两次学习的数据整合起来，

**Comment by 7eu7d7** [comment]
如果只是使用模型可以不需要训练，直接用预训练的模型，batch_size太小训练效果不好，想要训练一遍学习可以去https://featurize.cn/?s=3497fe87511142baa1408a228db40608租一个显卡，1小时之内就能跑完
