### ISSUE TITLE
 [Errno 32] Broken pipe问题

### ISSUE THREAD

**Issue by whitedustmoon1175** [7eu7d7/genshin_auto_fish#35]
File "E:\Download\python\envs\ysfish\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
    │              │     │              └ <Process(Process-3, initial daemon)>
    │              │     └ None
    │              └ <_io.BufferedWriter name=4>
    └ <class 'multiprocessing.reduction.ForkingPickler'>

BrokenPipeError: [Errno 32] Broken pipe
如何解决？

**Comment by whitedustmoon1175** [comment]
![image](https://user-images.githubusercontent.com/58837809/134287968-eef44e69-3b6f-4eaa-8460-efe45d37d6c2.png)

**Comment by whitedustmoon1175** [comment]
内存应该够吧，不知道要调哪个文件的num_workers

**Comment by pianfanshaan** [comment]
只用模型可以不训练

**Comment by 7eu7d7** [comment]
把这一行的值改为0 https://github.com/7eu7d7/genshin_auto_fish/blob/0de1a1d6c6cff1a70424eb806263fb042ee36c85/yolox/exp/yolox_base.py#L26

**Comment by whitedustmoon1175** [comment]
好的谢谢

**Comment by whitedustmoon1175** [comment]
请问如何直接用模型不训练

**Comment by whitedustmoon1175** [comment]
改成0之后还是broken了（

**Comment by whitedustmoon1175** [comment]
> 只用模型可以不训练

请问如何只用模型不训练

**Comment by pianfanshaan** [comment]
> > 只用模型可以不训练
> 
> 请问如何只用模型不训练

作者回复我的:
如果只是使用模型可以不需要训练，直接用预训练的模型
我CUDA无法分配内存直接不用训练了 都调用显存了 你这个是调用yolox训练对吧

**Comment by ipuppet** [comment]
> 改成0之后还是broken了（

试试去掉--fp16，或者减少 batch size

**Comment by whitedustmoon1175** [comment]
> > > 只用模型可以不训练
> > 
> > 
> > 请问如何只用模型不训练
> 
> 作者回复我的:
> 如果只是使用模型可以不需要训练，直接用预训练的模型
> 我CUDA无法分配内存直接不用训练了 都调用显存了 你这个是调用yolox训练对吧

想问问预训练的模型在哪里？

**Comment by 7eu7d7** [comment]
> > > > 只用模型可以不训练
> > > 
> > > 
> > > 请问如何只用模型不训练
> > 
> > 
> > 作者回复我的:
> > 如果只是使用模型可以不需要训练，直接用预训练的模型
> > 我CUDA无法分配内存直接不用训练了 都调用显存了 你这个是调用yolox训练对吧
> 
> 想问问预训练的模型在哪里？

仔细看首页说明啊，下载了预训练的权重直接调用最下面的就可以了，权重链接首页有给。

**Comment by whitedustmoon1175** [comment]
好的谢谢

**Comment by whitedustmoon1175** [comment]
没用过Python所以问题比较小白，不好意思！
