### ISSUE TITLE
无法定位程序输入点  没玩过python 能看看啥情况么

### ISSUE THREAD

**Issue by cxs-fight** [7eu7d7/genshin_auto_fish#36]
![image](https://user-images.githubusercontent.com/37561354/134290222-e2cf2999-61b0-45bd-9a19-2be2ea6ed4eb.png)
![image](https://user-images.githubusercontent.com/37561354/134290283-2dddfd27-5e20-4863-95b0-5f055ce97629.png)

**Comment by liuyoude** [comment]
pycocotools没有安装成功，steup.py中的安装方式好像有问题，推荐用轮子安装，参考https://blog.csdn.net/qq_38828370/article/details/120228048

**Comment by cxs-fight** [comment]
> pycocotools没有安装成功，steup.py中的安装方式好像有问题，推荐用轮子安装，参考https://blog.csdn.net/qq_38828370/article/details/120228048

嗯 这样就可以
