### ISSUE TITLE
钓鱼精度问题

### ISSUE THREAD

**Issue by pianfanshaan** [7eu7d7/genshin_auto_fish#38]
存在脱钩情况 游戏表现也低于视频表现 想问一下是模型精度问题吗 训练的还不够的原因? 还是我电脑比较卡?导致点击信号没有及时传输进去? 想请教一下

**Comment by 7eu7d7** [comment]
如果在cpu上运行的话，速度会很慢，卡顿会对精度造成极大影响

**Comment by srf000001** [comment]
甚至将树叶在水中倒影的图形识别成鱼了哈哈。。
