### ISSUE TITLE
抛竿时报错only integer tensors of a single element can be converted to an index

### ISSUE THREAD

**Issue by hgjazhgj** [7eu7d7/genshin_auto_fish#4]
![image](https://user-images.githubusercontent.com/40085173/134112879-992a0af9-7859-4c83-ab8d-7b7521d7401d.png)
此时在若干报错出现后能够完成抛竿动作,但是期间抛竿的位置不会移动

**Comment by 7eu7d7** [comment]
这个情况应该是没有识别到鱼，换一个角度试试，进入钓鱼状态后鱼饵选掉花鳉的那个

**Comment by hgjazhgj** [comment]
请问如何修改代码可以像视频中一样展示识别分类结果的区域?

**Comment by hgjazhgj** [comment]
我的游戏画面属性是1920x1080,渲染精度1.0,关动态模糊he 垂直同步,其他拉满

**Comment by 7eu7d7** [comment]
识别分结果无法前台展示，会干扰截图的识别，现在识别的图像结果都存在img_tmp下面了

**Comment by hgjazhgj** [comment]
我在不同场景下尝试了自动钓鱼都有此报错,但是查看img_tmp中的分类结果都是正确的

**Comment by hgjazhgj** [comment]
我方才提交了pr #24 ,修复了本人遇到的问题
