### ISSUE TITLE
关于安装教程

### ISSUE THREAD

**Issue by niceRAM** [7eu7d7/genshin_auto_fish#40]
### 关于 pip 升级
不清楚作者是如何升级 pip 的，教程里的命令会不会报错。
以下是个人拙见，望参考：

pip 由于是 lib 模块，直接 `pip install pip -U` 升级的话可能存在权限问题，建议改成以下命令：
```cmd
python -m pip install pip -U
```
  根据 #2 的报错，以下命令也许也行？
```cmd
pip install pip -U --user
```

### 关于 yolox 安装
这个 emmmmmm，有点怪。
因为其他库的需要，我之前已经装过 msvc++ 14.0了，但我这里一直报`error: Microsoft Visual C++ 14.0 or greater is required`，如图。
![image](https://user-images.githubusercontent.com/23020764/134311088-ccbc1346-a0f9-4fa2-bedb-8ab4df6c0625.png)
![image](https://user-images.githubusercontent.com/23020764/134311256-0ac8942a-88cc-4eb9-be2f-8dbcbc4d315b.png)

不知道是不是需要额外设置什么环境变量，还是说我装的和被要求的 build 版本不对，又或许和我 OS 版本有关系？(Windows 10 19041.1237)
C++ 这方面不怎么擅长，我也尝试了用 conda 安装 msvc_runtime 再安装 yolox、或手动 clone yolox 的库进行安装，结果都是报这个错。

准备尝试重装一个 msvc 14.0 再试试，有进展再来更新。

**Comment by mroldx** [comment]
要装VStudio

**Comment by qw392281711** [comment]
解决了吗？我python requirements.py时就提示c++14了

**Comment by niceRAM** [comment]
> 要装VStudio

这种报错通常只需要装个buildtool就行了吧，以前安装torch、cupy之类都是这么解决的。
vsstudio太大了卸载也不好卸载干净，我抽空再调查调查好了，如果还不行，作为最终方案再考虑开个虚拟机试试

**Comment by niceRAM** [comment]
> 解决了吗？我python requirements.py时就提示c++14了

安装依赖时报这个错这个我也遇到了，我这里是装 torch 的时候编译失败。

因为我本来就装了 msvc-buildtool 14 ，怀疑是环境变量的问题。所以我先用这个命令自动装了其他依赖，然后手动安装 torch 的。
在官网选择自己需要的版本就能获取对应的版本的安装命令了。
> [Start Locally | PyTorch](https://pytorch.org/get-started/locally/#start-locally)

另外如果你装 torch 编译报错了，后面装 yolox 估计也会报错吧，我这里就是，现在还在看。
重装 msvc-buildtool 也试了，没起作用。现在看报错能确定多少还是和 torch 有点关系，也许可以试试把 msvc-buildtool 的 cl.exe 添加到环境变量试试……不过我一直没找到 msvc-buildtool 的安装目录，setuptools 的 cl 倒是有看到 emmmmm

**Comment by niceRAM** [comment]
还是没解决，最终选择在另一台装了 VS studio 的机器编译了再拿过来安装，如果有更好的对策再打开这个 Issue 吧

共享一下 Python3.6 下编译的 .whl 文件
[yolox-0.1.0-cp36-cp36m-win_amd64.whl](https://cdn.jsdelivr.net/gh/niceRAM/blog-images/img/genshin_auto_fish/2021/09/23/11-29-45-322-ac5e16.whl)

**Comment by YangLinus** [comment]
为啥我安装完torch和vs之后我在安装yolox的时候他还是显示没有torch模块，是我安装的torch1.71+cu101太新了吗

**Comment by niceRAM** [comment]
> 为啥我安装完torch和vs之后我在安装yolox的时候他还是显示没有torch模块，是我安装的torch1.71+cu101太新了吗

依赖要求1.7+没问题，应该纯粹是torch安装的问题吧。你怎么装的touch，在Python控制台里 `import touch` 能成功吗
