### ISSUE TITLE
pip安装cuda失败

### ISSUE THREAD

**Issue by YangLinus** [7eu7d7/genshin_auto_fish#41]
ERROR: You must give at least one requirement to install (see "pip help install")
请问一定要安装和本机同一版本的cuda吗？
还有我在执行YOLOX的时候显示No module named 'torch'我认为是我pyHook的问题，但我重新安装还是无法解决

**Comment by 7eu7d7** [comment]
pytroch没安装，运行requirements.py时候应该还有其他报错
