### ISSUE TITLE
原神鱼群数据集沒有了

### ISSUE THREAD

**Issue by Eternal-Blue-Sky** [7eu7d7/genshin_auto_fish#42]
此项可能不存在或不再可用
此项可能已被删除或过期，或者你没有查看权限。有关详细信息，请与此项的所有者联系。

**Comment by kinglwx** [comment]
此项可能不存在或不再可用
此项可能已被删除或过期，或者你没有查看权限。有关详细信息，请与此项的所有者联系。

**Comment by LemOnByn** [comment]
万事俱备只差数据集了：）

**Comment by 7eu7d7** [comment]
在迅雷云盘也传了一份
https://github.com/7eu7d7/genshin_auto_fish#:~:text=%E4%B8%8B%E8%BD%BD%E6%95%B0%E6%8D%AE%E9%9B%86%E5%B9%B6%E8%A7%A3%E5%8E%8B%EF%BC%9A%E5%8E%9F%E7%A5%9E%E9%B1%BC%E7%BE%A4%E6%95%B0%E6%8D%AE%E9%9B%86%2C%20%E6%95%B0%E6%8D%AE%E9%9B%86(%E8%BF%85%E9%9B%B7%E4%BA%91%E7%9B%98%3Augha)
