### ISSUE TITLE
[YOLO 训练报错]'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by LemOnByn** [7eu7d7/genshin_auto_fish#43]
![image](https://user-images.githubusercontent.com/49295878/134348640-ed3dff0f-63b0-4311-801f-60799906b48b.png)
好像是训练完成后村output数据时数据类型出现了问题，这个是为什么？
numpy的版本是
numpy                   1.19.5

**Comment by LemOnByn** [comment]
![image](https://user-images.githubusercontent.com/49295878/134359095-54a225fa-0f15-4c7b-a1c8-bdb2cc16cbd8.png)
补一张截图，求大佬看看原因

**Comment by srf000001** [comment]
我也报了你下面图上这个 yolox.core.launch:98的错误，以及最终AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'，暂时无解

**Comment by LemOnByn** [comment]
> 我也报了你下面图上这个 yolox.core.launch:98的错误，以及最终AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'，暂时无解

AttributeError: module 'torch._C' has no attribute '_cuda_setDevice' 是你torch的版本或者英伟达的cuda组件没配好

**Comment by lcxw** [comment]
> ![image](https://user-images.githubusercontent.com/49295878/134359095-54a225fa-0f15-4c7b-a1c8-bdb2cc16cbd8.png)
> 补一张截图，求大佬看看原因

报错的地方我给改为了`num = operator.index(int(num))`
![image](https://user-images.githubusercontent.com/19720270/134384723-a0d188a6-4ba2-4f79-ab5e-c8b637e63a16.png)
