### ISSUE TITLE
模拟鼠标点击失败

### ISSUE THREAD

**Issue by ll789899** [7eu7d7/genshin_auto_fish#44]
![image](https://user-images.githubusercontent.com/45455546/134351868-a30dd948-1ee5-42d9-bf0c-c52e0cb8bea7.png)
到选铒的地方就会卡住 同样在鱼上钩的时候也不会起杆

**Comment by 7eu7d7** [comment]
分辨率不对吧，现在只支持1920*1080的分辨率

**Comment by ll789899** [comment]
> 分辨率不对吧，现在只支持1920*1080的分辨率

我是全屏1920*1080 ，鼠标能自动移到鱼饵选择框上 但是似乎模拟不了点击

**Comment by pianfanshaan** [comment]
> > 分辨率不对吧，现在只支持1920*1080的分辨率
> 
> 我是全屏1920*1080 ，鼠标能正常自动移到鱼饵选择框上 但是似乎模拟不了点击

我有过这个报错 重新启动命令就没事了

**Comment by ll789899** [comment]
> > > 分辨率不对吧，现在只支持1920*1080的分辨率
> > 
> > 
> > 我是全屏1920*1080 ，鼠标能正常自动移到鱼饵选择框上 但是似乎模拟不了点击
> 
> 我有过这个报错 重新启动命令就没事了

命令行报错貌似是因为识别不到鱼  我是模拟不了鼠标点击事件🤣 但是命令行又似乎没有这个的异常

**Comment by ll789899** [comment]
> > > > 分辨率不对吧，现在只支持1920*1080的分辨率
> > > 
> > > 
> > > 我是全屏1920*1080 ，鼠标能正常自动移到鱼饵选择框上 但是似乎模拟不了点击
> > 
> > 
> > 我有过这个报错 重新启动命令就没事了
> 
> 命令行报错貌似是因为识别不到鱼 我是模拟不了鼠标点击事件🤣 但是命令行又似乎没有这个的异常
> 环境是：Win11 GPU启动 1920*1080全屏游戏

**Comment by ll789899** [comment]
不好意思 没问题了 我一直以为只要走到鱼池旁边开启就好了 。原来需要自己先进入钓鱼状态🤣
