### ISSUE TITLE
安装yolox失败

### ISSUE THREAD

**Issue by DragonYang-code** [7eu7d7/genshin_auto_fish#46]
(ysfish) C:\Users\xx\Downloads\genshin_auto_fish>python setup.py develop
running develop
running egg_info
writing yolox.egg-info\PKG-INFO
writing dependency_links to yolox.egg-info\dependency_links.txt
writing top-level names to yolox.egg-info\top_level.txt
D:\Anaconda\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:339: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'yolox.egg-info\SOURCES.txt'
writing manifest file 'yolox.egg-info\SOURCES.txt'
running build_ext
D:\Anaconda\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:274: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'yolox._C' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by pianfanshaan** [comment]
需要C++14 把他安装了吧 教程上网搜

**Comment by DragonYang-code** [comment]
用是可以用了，就是寻找目标找很久，yolox训练时出现以下错误
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by DragonYang-code** [comment]
上面那个问题也解决了，就是现在运行老是报这个错误
Traceback (most recent call last):
  File "fishing.py", line 190, in <module>
    main(exp, args)
  File "fishing.py", line 148, in main
    start_fishing(predictor, agent)
  File "fishing.py", line 158, in start_fishing
    ff.do_fish()
  File "C:\Users\杨龙\Downloads\genshin_auto_fish\fisher\environment.py", line 103, in do_fish
    if self.fish_list[0]!=self.last_fish_type:
IndexError: list index out of range

**Comment by pianfanshaan** [comment]
> 上面那个问题也解决了，就是现在运行老是报这个错误
> Traceback (most recent call last):
> File "fishing.py", line 190, in
> main(exp, args)
> File "fishing.py", line 148, in main
> start_fishing(predictor, agent)
> File "fishing.py", line 158, in start_fishing
> ff.do_fish()
> File "C:\Users\杨龙\Downloads\genshin_auto_fish\fisher\environment.py", line 103, in do_fish
> if self.fish_list[0]!=self.last_fish_type:
> IndexError: list index out of range

有可能是这个错误
[https://github.com/7eu7d7/genshin_auto_fish/issues/64](url)
