### ISSUE TITLE
鱼儿上钩后不会自动收杆

### ISSUE THREAD

**Issue by ASimpleIronBlock** [7eu7d7/genshin_auto_fish#5]
https://user-images.githubusercontent.com/62505063/134113588-0783b83b-caf3-4e5a-aadc-b0edf534e293.mp4

![image](https://user-images.githubusercontent.com/62505063/134113705-2b83f09c-062f-41d6-b1d9-bf1f6f2f2108.png)
![image](https://user-images.githubusercontent.com/62505063/134113732-90d4344f-27dd-4aef-b2c9-e2f5245372ca.png)
游戏全屏了 使用的管理员权限运行的程序 
启动程序的指令:python fishing.py image -f yolox/exp/yolox_tiny_fish.py -c weights/best_tiny3.pth --conf 0.25 --nms 0.45 --tsize 640 --device cpu
游戏的显示设置(不知道会不会和这个有关系):
![image](https://user-images.githubusercontent.com/62505063/134113860-623336bd-2ecc-4c6f-a053-242b4dabd148.png)

**Comment by 7eu7d7** [comment]
画面要设置为1920x1080，目前还没做分辨率适配
