### ISSUE TITLE
第三步yolox训练错误/配置一晚上，0鱼，我才是双输玩家吧。

### ISSUE THREAD

**Issue by srf000001** [7eu7d7/genshin_auto_fish#54]
UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")

2021-09-22 22:27:06 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (20212), thread 'MainThread' (20208):

AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

也可能因为我是AMD显卡，百度了一下，好像AMD显卡不支持cuda。
不过按作者readme中说的，应该不需要显卡参与也可以。

**Comment by mroldx** [comment]
小伙我跟你一样

**Comment by 7eu7d7** [comment]
只用来钓鱼的话不需要训练，用预训练的模型就可以

**Comment by srf000001** [comment]
是跳过yolox训练和DQN训练直接进行最后一步运行AI吗，
感谢你的提示和反馈，我继续尝试下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月22日(星期三) 晚上10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [7eu7d7/genshin_auto_fish] 第三步yolox训练错误/配置一晚上，0鱼，我才是双输玩家吧。 (#54)





 
只用来钓鱼的话不需要训练，用预训练的模型就可以
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
