### ISSUE TITLE
 CUDA out of memory

### ISSUE THREAD

**Issue by lslwsjly** [7eu7d7/genshin_auto_fish#56]
RuntimeError: CUDA out of memory. Tried to allocate 5.49 GiB (GPU 0; 8.00 GiB total capacity; 24.06 MiB already allocated; 6.59 GiB free; 54.00 MiB reserved in total by PyTorch)

即使我把batch_size调到1，也不行。不管我batch size设置多少，Tried to allocate都是5G多

**Comment by 7eu7d7** [comment]
https://github.com/7eu7d7/genshin_auto_fish/issues/32
