### ISSUE TITLE
程序正常运行但是游戏里没反应。

### ISSUE THREAD

**Issue by srf000001** [7eu7d7/genshin_auto_fish#58]
![EK%KB~@QVXG_1L(EFF`~YGR](https://user-images.githubusercontent.com/55014244/134369623-f0f0c58a-cf32-4ac3-b2d2-d70402499ef2.png)

1、游戏中站在鱼池边，未进入钓鱼状态，运行后人物会左右转向，会有普攻动作（出发鼠标左键），但不会自动进入钓鱼状态。
2、游戏中已进入钓鱼状态，运行后游戏中无反应，程序正常运行。

**Comment by congmingwensi** [comment]
同样问题，训练运行正常，游戏中运行后出现报错：
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([80, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([6, 96, 1, 1]).
三次后程序退出

**Comment by 7eu7d7** [comment]
要手动进入钓鱼状态，选中第一个鱼饵，进入钓鱼状态再启动
