### ISSUE TITLE
友情提醒 pip版本必须是20.1.1的，最新版本安装参数不匹配全是错

### ISSUE THREAD

**Issue by SwrodKing** [7eu7d7/genshin_auto_fish#64]
pip安装可以参考这个教程https://blog.csdn.net/weixin_41010198/article/details/107174343

还有下载的慢请变更pip默认镜像源，我用的清华大学 https://pypi.tuna.tsinghua.edu.cn/simple/
pip config set global.index-url  https://pypi.tuna.tsinghua.edu.cn/simple/

还有还有，我建议可以的话大佬可以搞得动态学和识别鱼种匹配钓竿和鱼饵，当然纯粹建议，哈哈哈

**Comment by mroldx** [comment]
xd, 20,1,1的whl文件还有吗,官网下架了找不到

**Comment by SwrodKing** [comment]
pip20.1.1 https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl
