### ISSUE TITLE
python requirements.py

### ISSUE THREAD

**Issue by pkhk-1** [7eu7d7/genshin_auto_fish#68]
Command errored out with exit status 128: git clone -q https://github.com/philferriere/cocoapi.git '

**Comment by SevenKin** [comment]
安装个git

**Comment by pianfanshaan** [comment]
> 安装个git

这不是没装git的问题 是网络问题 我也有 不过这个不影响后面跑 你翻翻closed issue有解释这个问题的#27

**Comment by nwdxlgzs** [comment]
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\wangyu~1\appdata\local\temp\pip-req-build-8nz7t14l
  Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\WANGYU~1\AppData\Local\Temp\pip-req-build-8nz7t14l'
  Resolved https://github.com/philferriere/cocoapi.git to commit 2929bd2ef6b451054755dfd7ceb09278f935f7ad
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python37\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WANGYU~1\\AppData\\Local\\Temp\\pip-req-build-8nz7t14l\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\WANGYU~1\\AppData\\Local\\Temp\\pip-req-build-8nz7t14l\\PythonAPI\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\WANGYU~1\AppData\Local\Temp\pip-pip-egg-info-x53khlj0'
         cwd: C:\Users\WANGYU~1\AppData\Local\Temp\pip-req-build-8nz7t14l\PythonAPI
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WANGYU~1\AppData\Local\Temp\pip-req-build-8nz7t14l\PythonAPI\setup.py", line 4, in <module>
        import numpy as np
      File "C:\Users\wangyuheng\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 138, in <module>
        from . import _distributor_init
      File "C:\Users\wangyuheng\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
        WinDLL(os.path.abspath(filename))
      File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
    ----------------------------------------
WARNING: Discarding git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nwdxlgzs** [comment]
迷惑

**Comment by pkhk-1** [comment]
> > 安装个git
> 
> 这不是没装git的问题 是网络问题 我也有 不过这个不影响后面跑 你翻翻closed issue有解释这个问题的#27

![image](https://user-images.githubusercontent.com/82303451/134604958-6db5c596-155d-41b8-acb8-32eaa0d0b7d6.png)
科学上网以后，再次运行相同命令，好像会跳过这个，但是build wheel又会很多错误

**Comment by pianfanshaan** [comment]
> > > 安装个git
> > 
> > 
> > 这不是没装git的问题 是网络问题 我也有 不过这个不影响后面跑 你翻翻closed issue有解释这个问题的#27
> 
> ![image](https://user-images.githubusercontent.com/82303451/134604958-6db5c596-155d-41b8-acb8-32eaa0d0b7d6.png)
> 科学上网以后，再次运行相同命令，好像会跳过这个，但是build wheel又会很多错误

C++没安装
