### ISSUE TITLE
Microsoft Visual C++ 14.0 or greater is required.

### ISSUE THREAD

**Issue by JYL32tgr** [7eu7d7/genshin_auto_fish#7]
C:\Users\Anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:274: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'yolox._C' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

是不是还得装C++什么的。。非程序员头大了，大佬能搞个一键安装吗？谢谢大佬

**Comment by Ox1O5** [comment]
> C:\Users\Anaconda3\envs\ysfish\lib\site-packages\torch\utils\cpp_extension.py:274: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
> warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
> building 'yolox._C' extension
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> 
> 是不是还得装C++什么的。。非程序员头大了，大佬能搞个一键安装吗？谢谢大佬

参考这个链接 https://zhuanlan.zhihu.com/p/165008313 直接用 Visual C++ 14.2 编译器的 standalone

**Comment by kill110** [comment]
没用，还是报错。安装了vs2022？？？
