### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xz304776** [7eu7d7/genshin_auto_fish#76]
![image](https://user-images.githubusercontent.com/77931226/134535898-5415a888-1f36-4daa-b44d-7152ae18a005.png)

**Comment by Be-a-Solitude** [comment]
同问

**Comment by Be-a-Solitude** [comment]
> 同问

 我重新配置了一下环境也还是会溢出

**Comment by yuanyehome** [comment]
这说明你这个池子没鱼了或者程序没检测到鱼

**Comment by xz304776** [comment]
> > 同问
> 
> 我重新配置了一下环境也还是会溢出

已解决，是要在游戏中按r，之前都是在命令界面按得

**Comment by Crysmart** [comment]
> > > 同问
> > 
> > 
> > 我重新配置了一下环境也还是会溢出
> 
> 已解决，是要在游戏中按r，之前都是在命令界面按得

不行，游戏里面按r后，左右看了两下还是一样的报错
