### ISSUE TITLE
Is there a demo of this repo?

### ISSUE THREAD

**Issue by Keiku** [7eu7d7/genshin_auto_fish#84]
It's hard to understand in Chinese.

**Comment by jinianyoushang** [comment]
ahhaha

**Comment by Maaaaaxcen** [comment]
【[原神]AI全自动钓鱼，完全解放双手(开源)！DQN+YOLOX+OpenCV+迁移学习。-哔哩哔哩】https://b23.tv/Azar6Z
here's  a demo for it, but I think google translate may work for you to translate the readme. Since it is just a project made at spare time I think, the contributor may not translate it into English.
