### ISSUE TITLE
问一下，我这样算运行成功了吗？为什么它不进行钓鱼操作？使用的是显卡运算

### ISSUE THREAD

**Issue by 000001919** [7eu7d7/genshin_auto_fish#88]
![image](https://user-images.githubusercontent.com/78247561/134697372-64fedd30-a828-4cc2-9181-822eb6b54fe5.png)

**Comment by DragonYang-code** [comment]
会不会是没启用管理员权限

**Comment by 000001919** [comment]
确实是这样，万分感谢

**Comment by 000001919** [comment]
确实是这样，万分感谢
