### ISSUE TITLE
yolox_tiny.pth这个文件找不到

### ISSUE THREAD

**Issue by wzphood** [7eu7d7/genshin_auto_fish#9]
执行YOLOX训练时报错
[Errno 2] No such file or directory: 'weights/yolox_tiny.pth'

**Comment by wudih146** [comment]
同样

**Comment by 7eu7d7** [comment]
https://github.com/7eu7d7/genshin_auto_fish/releases/tag/weights 下载里面3个pth

**Comment by wzphood** [comment]
> https://github.com/7eu7d7/genshin_auto_fish/releases/tag/weights 下载里面3个pth
我下载了...也放在weights里了，但是那三个path里没有叫yolox_tiny的...

**Comment by 7eu7d7** [comment]
> > https://github.com/7eu7d7/genshin_auto_fish/releases/tag/weights 下载里面3个pth
> > 我下载了...也放在weights里了，但是那三个path里没有叫yolox_tiny的...

是运行训练吗，那个是yolox官方提供的预训练模型，https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_tiny.pth
