### ISSUE TITLE
anaconda为什么死活装不上库

### ISSUE THREAD

**Issue by mroldx** [7eu7d7/genshin_auto_fish#97]
![image](https://user-images.githubusercontent.com/34847828/134762620-aede6c4f-4cac-4fc4-aa75-fb1fc4b3e993.png)
我这明明有setuptools
![image](https://user-images.githubusercontent.com/34847828/134762648-60f1c427-ec8e-414d-b7f8-20ce8a26e670.png)
这是哪出了问题,我在此环境执行任何一个install命令都装不了库

**Comment by mroldx** [comment]
![image](https://user-images.githubusercontent.com/34847828/134762677-e856c7bd-bbec-49b2-af5b-3f8d4dc412b4.png)
![image](https://user-images.githubusercontent.com/34847828/134762685-b48fe9bb-5e53-42ed-abca-13c72cdd9778.png)

**Comment by mroldx** [comment]
anaconda版本2021.5

**Comment by mroldx** [comment]
管理员运行
![image](https://user-images.githubusercontent.com/34847828/134762720-57ca09d0-ddf7-4bc2-bb1c-9ec9a168b52c.png)

**Comment by mroldx** [comment]
我发现了只要安装pyautogui这个库就报setuptools找不到
在执行python requirements.py就已经报了这个错误

**Comment by mroldx** [comment]
我已经换了五个环境都是这个错误,必现

**Comment by wasabiegg** [comment]
python -m pip install -U pip setuptools

**Comment by mroldx** [comment]
xdm终于跑起来了

**Comment by mroldx** [comment]
妈的直接下包装  https://pypi.org/project/PyAutoGUI/#files
