### ISSUE TITLE
运行python requirements.py出现错误

### ISSUE THREAD

**Issue by q764447890** [7eu7d7/genshin_auto_fish#98]
![python requirements](https://user-images.githubusercontent.com/26245718/134766944-cc15687b-cf6f-4f4f-8d58-5634a357ff36.png)

**Comment by WeiZhenOoooo** [comment]
安装vs编译器

**Comment by loy1020** [comment]
好像是需要VC++ 14.0

**Comment by q764447890** [comment]
> 好像是需要VC++ 14.0

ok了,安装后已解决

**Comment by fervor-H** [comment]
> > 好像是需要VC++ 14.0
> 
> ok了,安装后已解决

请问如何在虚拟环境装vc++ 14.0噢

**Comment by q764447890** [comment]
> > > 好像是需要VC++ 14.0
> > 
> > 
> > ok了,安装后已解决
> 
> 请问如何在虚拟环境装vc++ 14.0噢

不懂 
这是vc++14安装包
链接：https://pan.baidu.com/s/1AOl1-UgvU7b8Eba6Vl-moQ 
提取码：wob9
